### ISSUE TITLE
"make local" broken

### ISSUE THREAD

**Issue by b509** [mrparkers/terraform-provider-keycloak#1000]
Commit from yesterday (by @thomasdarimont, commit id  d65c3b87b47fc609fe0252bf6d4a4a26fcac7f67) broke my local environment: local keycloak doesn't come up in fresh repo after "make build" and "make local", error message in keycloak is

> [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.io.FileNotFoundException: /opt/keycloak/lib/../providers/custom-user-federation-example-all.jar (Is a directory)

Could someone give me a pointer how to fix this?

Dev Environment: Windows Subsystem Linux (Ubuntu 22) on Win10 host

**Comment by thomasdarimont** [comment]
you need to build the example provider first, try:

`make user-federation-example`

**Comment by b509** [comment]
Thanks yes, that worked (after installing java 11). Gonna add some notes to the README with my contribution
