### ISSUE TITLE
missing docs for resources / data sources

### ISSUE THREAD

**Issue by mrparkers** [mrparkers/terraform-provider-keycloak#112]
This is a reminder for me to add missing docs for the following resources and data sources:

resources:

- keycloak_openid_client_authorization_resource
- keycloak_openid_client_authorization_scope
- keycloak_openid_client_authorization_permission
- keycloak_openid_client_service_account_role
- keycloak_oidc_identity_provider
- keycloak_user_template_importer_identity_provider_mapper
- keycloak_attribute_to_role_identity_provider_mapper
- keycloak_hardcoded_role_identity_provider_mapper
- keycloak_hardcoded_attribute_identity_provider_mapper

data sources:

- keycloak_openid_client_authorization_policy

I will try to add these when I have time, and I will happily accept PRs from anyone who is interested in contributing these.

**Comment by dlechevalier** [comment]
Hi, it looks like all the stuff has been done yet. Isn't it?

**Comment by mrparkers** [comment]
Hi @dlechevalier, I think the current list in the main post is up to date with what is missing.

**Comment by diamondq** [comment]
Maybe I'm missing something, but I still don't see docs for most of them. Specifically, only 

```
resource: keycloak_oidc_identity_provider
resource: keycloak_openid_client_service_account_role
datasource: keycloak_openid_client_authorization_policy
```

are documented. I don't see the rest anywhere.

**Comment by marcoreni** [comment]
Hei @diamondq, have you checked [here](https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs)?

**Comment by diamondq** [comment]
I did. I was specifically looking for the `keycloak_openid_client_authorization_XXX` docs, such as `keycloak_openid_client_authorization_resource`.  It should under the resources section; don't see it.
I even tried jumping directly the URL it should be:
[https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/openid_client_authorization_resource](https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/openid_client_authorization_resource), but no luck.

**Comment by shdpl** [comment]
I think it just does not appear in the "KEYCLOAK DOCUMENTATION" browser.
