### ISSUE TITLE
clients: support configuring of Scope

### ISSUE THREAD

**Issue by BernhardBerbuir** [mrparkers/terraform-provider-keycloak#117]
Currently the scope of a client (__ATTENTION:__ do not do not confuse with _Client Scopes_ / _Scope Mapping_) can not beconfigured. The default configuration uses `Full Scope Allowed=TRUE`. I want to be able to set this to `Full Scope Allowed=FALSE`.

The REST API requires to update the client with a [clientrepresentation](https://www.keycloak.org/docs-api/6.0/rest-api/index.html#_clientrepresentation) where `fullScopeAllowed=false`

**Comment by mrparkers** [comment]
Closed via #118
