### ISSUE TITLE
data source for realm keys

### ISSUE THREAD

**Issue by BernhardBerbuir** [mrparkers/terraform-provider-keycloak#125]
Provide a data source for retrieving keys of a realm.
The REAST API of Keycloak provides a `GET` method for [realm keys](https://www.keycloak.org/docs-api/6.0/rest-api/index.html#_key_resource)
Filtering by algorithm and other attributes would be useful.

**Comment by mrparkers** [comment]
This is a good idea!  I'll add this to my personal backlog unless someone else is willing to take this on.

**Comment by mrparkers** [comment]
Oops, I didn't realize you already opened #126 :smile:

**Comment by BernhardBerbuir** [comment]
No Feature Request without Pull Request :smile:
