### ISSUE TITLE
Support for identity providers

### ISSUE THREAD

**Issue by nagytech** [mrparkers/terraform-provider-keycloak#141]
It would be good to provide a resource for managing Identity Providers.

https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_identity_providers_resource

**Comment by mrparkers** [comment]
So this is awkward - but this provider does actually support identity providers:

- oidc: https://github.com/mrparkers/terraform-provider-keycloak/blob/master/provider/resource_keycloak_oidc_identity_provider.go
- saml: https://github.com/mrparkers/terraform-provider-keycloak/blob/master/provider/resource_keycloak_saml_identity_provider.go

The awkward part is that the PRs that were merged to add these didn't include docs, and I just haven't gotten around to writing those yet 😞 (#112).  I apologize that these resources aren't very discoverable.

**Comment by nagytech** [comment]
Cool thanks.  If I get some time I might try and help out.

**Comment by wwjn** [comment]
I've found an issue with the import of an oidc provider.

```
module.master_realm.keycloak_oidc_identity_provider.google: Importing from ID "master/google"...
2019/08/08 09:28:43 [TRACE] [walkImport] Exiting eval tree: module.master_realm.keycloak_oidc_identity_provider.google (import id: master/google)
2019/08/08 09:28:43 [TRACE] vertex 'root.module.master_realm.keycloak_oidc_identity_provider.google (import id: master/google)': expanding/walking dynamic subgraph
module.master_realm.keycloak_oidc_identity_provider.google: Import complete!
  Imported keycloak_oidc_identity_provider (ID: google)
2019/08/08 09:28:43 [TRACE] dag/walk: added new vertex: "import module.master_realm.keycloak_oidc_identity_provider.google result: google"
2019/08/08 09:28:43 [TRACE] dag/walk: walking "import module.master_realm.keycloak_oidc_identity_provider.google result: google"
2019/08/08 09:28:43 [TRACE] vertex 'root.master_realm.import module.master_realm.keycloak_oidc_identity_provider.google result: google': walking
2019/08/08 09:28:43 [TRACE] vertex 'root.master_realm.import module.master_realm.keycloak_oidc_identity_provider.google result: google': evaluating
2019/08/08 09:28:43 [TRACE] [walkImport] Entering eval tree: import module.master_realm.keycloak_oidc_identity_provider.google result: google
2019/08/08 09:28:43 [TRACE] root.master_realm: eval: *terraform.EvalSequence
2019/08/08 09:28:43 [TRACE] root.master_realm: eval: *terraform.EvalGetProvider
2019/08/08 09:28:43 [TRACE] root.master_realm: eval: *terraform.EvalRefresh
module.master_realm.keycloak_oidc_identity_provider.google: Refreshing state... (ID: google)
2019-08-08T09:28:43.556+1000 [DEBUG] plugin.terraform-provider-keycloak_v1.9.0: 2019/08/08 09:28:43 [DEBUG] Sending GET to /auth/admin/realms/master/identity-provider/instances/
```

Seems like the `alias` field given by the second part of the resource id isn't added to the `alias` field on import.

https://github.com/mrparkers/terraform-provider-keycloak/blob/e899c32196531e77d5361475030aaf6187192926/provider/generic_keycloak_identity_provider.go#L148
