### ISSUE TITLE
Add support for default groups

### ISSUE THREAD

**Issue by fharding1** [mrparkers/terraform-provider-keycloak#144]
AFAICT, there is no way to specify default groups at the moment. This would be fairly easy to implement, since it's a really basic resource. The relevant endpoints are:

    GET /{realm}/default-groups (returns a list of all default groups)
    PUT /{realm}/default-groups/{groupId} (add a group to the list of default groups)
    DELETE /{realm}/default-groups/{groupId} (delete a group from the list of default groups)

The first way that comes to mind for how this could be implemented is having a very basic resource for each default group that simply maps a realm id to a group id. This maps very well to the keycloak API. The HCL would look something look this:

```
resource "keycloak_group" "example_group" {
  realm_id = "${keycloak_realm.realm.id}"
  name     = "example-group"
}

resource "keycloak_default_group" "example_group" {
  realm_id = "${keycloak_realm.realm.id}"
  group_id = "${keycloak_group.example_group.id}"
}
```

We could also have a default groups property on realms, or have a default groups resource, or have a default group property on groups, but I don't think those solutions map very well to the API. Additionally, we could specify it on the realm, but then we get into a scenario where if a realm references groups that need to be created after the realm is then there's a potential deadlock.

I would be happy to take a crack at adding this feature.

**Comment by mrparkers** [comment]
Hi @fharding1, thanks for the issue!  You're right that the provider does not currently support this, I'd be happy to accept a PR that adds this functionality.

I think the HCL you posted makes sense and is the best approach.  I agree that adding default groups on the `keycloak_realm` resource does not make sense, mostly because there would be no way to apply your entire configuration with a single run of `terraform apply`, like you mentioned.  Also, that resource has too many attributes on it already 😄 

Feel free to let me know if you have any questions or run into issues while working on this.

**Comment by mrparkers** [comment]
Something else I just thought of - it may be a good idea to do some extra validation against using the `keycloak_group_memberships` resource on a default group, or at least document the pitfalls of using both of these resources on the same group.

**Comment by fharding1** [comment]
Because of:

`Note that this resource attempts to be an authoritative source over group members.`

Do you think it makes sense to just not allow a default group to be used alongside `keycloak_group_memberships`?

**Comment by fharding1** [comment]
So I'm actually thinking it might make sense to have one `keycloak_default_groups` resource per realm which looks like this:

```hcl
resource "keycloak_default_group" "example_group" {
  realm_id = "${keycloak_realm.realm.id}"
  group_ids = ["${keycloak_group.example_group.id}", "${keycloak_group.example_group_2.id}"]
}
```

This would be similar to how the `keycloak_group_memberships` resource works. It makes PUT/DELETE a bit weirder, but the GET endpoint makes a lot more sense.
