### ISSUE TITLE
Errors aren't checked properly when removing a group membership user from a group

### ISSUE THREAD

**Issue by fharding1** [mrparkers/terraform-provider-keycloak#145]
https://github.com/mrparkers/terraform-provider-keycloak/blob/0f1fe1bad1e107f0199bb93466b18003450e7a79/provider/resource_keycloak_group_memberships.go#L106

I think this code should be returning `err` rather than `nil`. As-is, if there's an error removing a user from a group nothing will happen.

**Comment by mrparkers** [comment]
Good catch, I agree.  You can make this change in the PR you have open if you'd like.

Technically, the idiomatic way to handle this in Terraform is by using [partial state](https://www.terraform.io/docs/extend/writing-custom-providers.html#error-handling-amp-partial-state). In this example, if the provider was able to remove three out of four group members, it shouldn't completely blow up, but rather ensure that the resulting state correctly contains the remaining member.

Eventually I plan on revisiting these resources to improve the error handling.
