### ISSUE TITLE
Refactor KeycloakClient to use oauth2 and clientcredentials libraries

### ISSUE THREAD

**Issue by fharding1** [mrparkers/terraform-provider-keycloak#148]
Much of the functionality in `KeycloakClient` for logging in and refreshing the access token seems to re-implement behavior already implemented in [golang.org/x/oauth2](https://godoc.org/golang.org/x/oauth2) and [golang.org/x/oauth2/clientcredentials](https://godoc.org/golang.org/x/oauth2/clientcredentials). This issue includes research into whether those libraries would be sufficient, and refactoring `KeycloakClient` to use them if they are. I would be happy to take this on.

**Comment by mrparkers** [comment]
I agree, it would probably be better to use an official OAuth2 implementation rather than one implemented in this project.

Feel free to look into this and submit a PR if this is something you're interested in 😄 

Thanks for the issue!

**Comment by fharding1** [comment]
Of course, happy to help out! I actually just submitted a PR to golang/oauth2 that should help out with this (it's still possible to use golang/oauth2 without it but it's a bit more annoying), so I'll see where that goes... 

https://github.com/golang/oauth2/pull/396

**Comment by mrparkers** [comment]
Nice, I like the initiative!  I think the PR you submitted has valid use cases even without this provider in mind.
