### ISSUE TITLE
Certificate / Fingerprint outputs

### ISSUE THREAD

**Issue by jleclanche** [mrparkers/terraform-provider-keycloak#161]
In the documentation, I can't find any exposed properties for a saml client's certificate, xml cert file, or cert fingerprint. Are those currently unimplemented/undocumented or am I blind? It would be great to have them.

**Comment by mrparkers** [comment]
I don't believe those are implemented.  For the most part, the SAML support for this provider is limited to what I needed at my previous employer and nothing else.

I can get to this in my free time, or you can contribute these features if you'd like.  I think most of these would be computed attributes on the `keycloak_realm` resource.

**Comment by jleclanche** [comment]
Gotcha. We're currently working on setting up keycloak for the [archlinux.org](https://archlinux.org) SSO, and we're using this module to terraform it.

I can try to work on a patch but both golang and terraform plugin development is well outside my comfort zone, it'll take me a while. If you can point me in the right direction it'll help.

**Comment by mrparkers** [comment]
Ah, that's cool.  I hope it works well for you.

If you don't feel comfortable contributing a fix, I can get to it some time this week for you.

If you do want to contribute, I'd start by running Keycloak locally and poking around in the GUI, while using the network tab of your browser to see what API calls are being made.

From there, we'd just need to add those properties to the [`keycloak_realm`](https://github.com/mrparkers/terraform-provider-keycloak/blob/master/provider/resource_keycloak_realm.go) resource as `Computed` attributes.

**Comment by jleclanche** [comment]
@mrparkers So I'm looking at this issue again. It appears what I want is defined here:
https://github.com/mrparkers/terraform-provider-keycloak/blob/a11355955b754d173535b51fca324d8ac6f03baa/keycloak/saml_client.go#L15

But… printing it into a string, it looks like it's null, despite it being defined in the UI.

**Comment by jleclanche** [comment]
I got it to show up in `.signing_certificate` with a weird workaround, specifying my own cert, then removing it, then adding it in `ignore_changes` lifecycle. Now, that doesn't close the bug, BUT:

I need the sha1 fingerprint of this. To do that, I need to base64 decode it. Terraform does have both base64decode() and sha1(), but sha1() can only take utf-8 text, not arbitrary binary data (which this is), cf. hashicorp/terraform#22996. It also does have oddly-specific base64sha256() and base64sha512(), but not the sha1 version. There's no reason these can't be sha256 or sha512 but the problem is, this is for a gitlab instance; gitlab uses omniauth-rails which doesn't appear to support sha2 (see omniauth/omniauth-saml#138)

Argh. Any chance you can fix the `signing_certificate` attribute and add a `signing_certificate_sha1` read-only attribute?

**Comment by mrparkers** [comment]
Hi @jleclanche.

I ended up fixing the issue with that attribute being set to `null` incorrectly, but that caused other issues that are related to this bug within the version of the Terraform SDK that this provider is using (https://github.com/hashicorp/terraform/pull/21806),

This provider is using the 0.12.1 SDK which is quite old now.  I'm going to spend some time this week trying to update it to the latest version and see if this will fix the issue you're having.

I can also add that attribute for you when I'm finished with this.

**Comment by mrparkers** [comment]
I bumped the SDK (converted to terraform-plugin-sdk) in #214, so I should be able to make more progress on this now.

**Comment by svenstaro** [comment]
Friendly bump. We kinda still need this. :)

**Comment by mrparkers** [comment]
Closed via #589
