### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by LoicAG** [mrparkers/terraform-provider-keycloak#164]
Hi there,

First of all thanks for this great provider, it has greatly simplified our management of Keycloak: we used to have a mixture of home-made scripts, manual management, and semi-automated exports/imports, which basically never worked well. Now everything is cleanly organized in terraform modules, making life much easier for my developer colleagues and myself (DevOps).

And now that our Keycloak instance is getting used more and more, we're hitting the timeout issue more often; would you consider making a new release soonish?

Cheers from Bordeaux, France,
Loïc

**Comment by mrparkers** [comment]
Hi, sorry for the delay! I just published 1.11.0 today 🚀

**Comment by LoicAG** [comment]
Awesome, thanks!
