### ISSUE TITLE
Support PKCE switch in Advanced Settings of openID Client

### ISSUE THREAD

**Issue by Pinguwien** [mrparkers/terraform-provider-keycloak#169]
Hi there,

perhaps I haven't found it yet, but I am missing the PKCE switch in the "Advanced Settings" - Tab of an openid client in keycloak (using v7). 
<img width="951" alt="Bildschirmfoto 2019-10-21 um 11 35 20" src="https://user-images.githubusercontent.com/3540413/67199132-c1cb1500-f400-11e9-9e81-fe7bc70b78e4.png">

As it is state of the art now also for SPAs to use authorization grant with PKCE enabled (source e.g. https://developer.okta.com/blog/2019/05/01/is-the-oauth-implicit-flow-dead) I'd hoped there was a possibility to add it via terraform provider, but I can't find it yet. Am I missing something? If not, it would be great to have it!

**Comment by mrparkers** [comment]
Hi @Pinguwien, thanks for the issue!

You aren't missing anything, this looks like a new configuration option that didn't exist in the version of Keycloak that I'm most familiar with (4.8.3.Final).  [While that version did support PKCE](https://github.com/alexashley/keycloak-pkce), there was no configuration for it nor was it mentioned in the docs.

I'd happily accept a PR to add this functionality if you are interested in contributing.  If not, that's fine too, although it may take some time before I get to this.

**Comment by Pinguwien** [comment]
so, I am staying at the hotel tomorrow and will have a look (and my ... almost first sight) at go and the implementation. Don't know if it works out, but will give it a try. Any hints on how to rapidly get a local dev env working would be great.

**Comment by mrparkers** [comment]
If you have the following installed:

- docker
- [jq](https://stedolan.github.io/jq/)
- make

You can run `make local` from the root directory of this project.  Once that's done, your local Keycloak instance will be available at http://localhost:8080.  The default creds are keycloak/password.

I should really write some developer docs to help explain this.

**Comment by Pinguwien** [comment]
My colleague @psanetra and me are working on this right now and will create a pr later on. In testing right now, with keycloak 6.0.1 from your image it worked. We had to add the whole "attributes" map from the keycloak rest api, and checked if other values would be overridden when you just set the pkce key/value. Good news: they don't. So the PR will only contain the PKCE switch for now. I think philip will send you the pr later on, for we remoted on his machine. We'll now test w/ keycloak 7.0.1 and our test client again (end-2-end, its a react testapp which has the client-side parameter for pkce enabled)

**Comment by mrparkers** [comment]
Perfect, nice work!

If you could also add this new attribute to one of the [existing test cases](https://github.com/mrparkers/terraform-provider-keycloak/blob/master/provider/resource_keycloak_openid_client_test.go), that would be much appreciated!
