### ISSUE TITLE
Terraformer / ProtocolMappers

### ISSUE THREAD

**Issue by Trois-Six** [mrparkers/terraform-provider-keycloak#182]
Hi,

I am working on a side project to this project: adding terraformer support for your provider. To do this, I decided to use your "sdk - keycloak go client" inside the code of your provider.

That said, I need new functions to retrieve slices of objects to import resources in terraformer. You can view the work I have done so far here: https://github.com/Trois-Six/terraform-provider-keycloak/tree/feat/terraformer and https://github.com/Trois-Six/terraformer/tree/feat/keycloak_provider.

For  the moment I can import these resources:

- [x] realms
  - [x] keycloak_realm
  - [x] keycloak_ldap_user_federation
  - [x] keycloak_ldap_full_name_mapper
  - [x] keycloak_ldap_group_mapper
  - [x] keycloak_ldap_msad_user_account_control_mapper
  - [x] keycloak_ldap_user_attribute_mapper
  - [x] keycloak_required_action
- [x] users
  - [x] keycloak_user
- [x] roles
  - [x] keycloak_role
- [x] scopes
  - [x] keycloak_openid_client_scope
  - [x] keycloak_openid_client_default_scopes
  - [x] keycloak_openid_client_optional_scopes
- [x] groups
  - [x] keycloak_group
  - [x] keycloak_group_memberships
  - [x] keycloak_group_roles
  - [x] keycloak_default_groups
- [x] openid_clients
  - [x] keycloak_openid_client
  - [x] keycloak_openid_client_service_account_role
  - [x] keycloak_openid_user_attribute_protocol_mapper
  - [x] keycloak_openid_user_property_protocol_mapper
  - [x] keycloak_openid_full_name_protocol_mapper
  - [x] keycloak_openid_audience_protocol_mapper

Would you accept to add new functions inside your code to support this effort ? (whereas it's not directly needed by the provider, but by terraformer).

Best regards,

Pierre

**Comment by mrparkers** [comment]
Hi @Trois-Six.

I have no problem at all with you adding extra functionality to the `keycloak` package to help support this.  I've actually been thinking that it may be appropriate to eventually pull the `keycloak` package out into its own GitHub repository so it can live independently of the provider, but I we can hold off on that for now.

**Comment by Trois-Six** [comment]
FYI, https://github.com/GoogleCloudPlatform/terraformer/pull/325.

**Comment by Trois-Six** [comment]
Merged in terraformer. Please test it and give me any feedbacks.
