### ISSUE TITLE
Implement realm events configuration

### ISSUE THREAD

**Issue by mmaldonado-wtsh** [mrparkers/terraform-provider-keycloak#187]
Hi,

First of all, thank you for this great work!

Would it be possible to implement events configuration in the provider?

Keycloak API documentation is available here:
- https://www.keycloak.org/docs-api/8.0/rest-api/index.html#_realmeventsconfigrepresentation
- https://www.keycloak.org/docs-api/8.0/rest-api/index.html#_realms_admin_resource

It might require the following methods:
- GET /{realm}/events/config
- PUT /{realm}/events/config

Thank you!

**Comment by mrparkers** [comment]
Yes, this should definitely be possible.  Unfortunately, I don't have the time to add new features at the moment, so someone else may have to pick this up.

If you're willing to submit a PR to add this feature, I'll be happy to help answer questions or point you in the right places.  Just let me know!

**Comment by mrparkers** [comment]
Closed via #211
