### ISSUE TITLE
Add defaultScopes to identity provider config

### ISSUE THREAD

**Issue by Pinguwien** [mrparkers/terraform-provider-keycloak#188]
Hi :) me again.

After using PKCE now and it works perfectly fine, I have another question. I am integrating a brokering scenario with AzureAD as an identity provider. thus, I need to set the default scopes to openid profile email. 

I've seen in https://github.com/mrparkers/terraform-provider-keycloak/blob/master/provider/resource_keycloak_oidc_identity_provider.go that there's an extra_config flag, which creates the appropriate json for "config: ..." - My desired config value is: 

```
config: {
    defaultScope: "openid profile email"
...
}
```
So for now, I just see that dummy-type in the repo, so my question is:

Is it possible to just add the param to extra_config without creating a PR? If yes, is it enough to do it just like this:
```
extra_config = {
    defaultScope = "openid email profile"
  }
```

if not, I think it would be enough to create the type, isn't it? But imho the aforementioned part should be enough, due to the extra_config type is just a kind of dynamic key/value store, isn't it? I just want to get that clear in my head, sorry ;)

**Comment by tomrutsaert** [comment]
Yes

```
extra_config = {
     defaultScope = "openid email profile"
}
```

will do the trick

**Comment by mrparkers** [comment]
Closing this since it seems the original question has been answered, thanks @tomrutsaert!
