### ISSUE TITLE
[Groups] - Add attributes

### ISSUE THREAD

**Issue by AdrienFromToulouse** [mrparkers/terraform-provider-keycloak#194]
Hello @mrparkers ,

Thanks for maintaining this awesome project!

I would like to contribute to it but before making any PR I wanted to get your feedback.
It seems not possible at the moment to add attributes: 
https://github.com/mrparkers/terraform-provider-keycloak/blob/master/keycloak/group.go#L8-L17

Is there any particular complexity to be expected for not being implemented yet?

If not I would like to tackle the issue. Would you agree?

**Comment by mrparkers** [comment]
Hi @AdrienFromToulouse, thanks for opening an issue.

I don't think adding support for group attributes would be particularly complex.  When I implemented the `keycloak_group` resource, I didn't have a need for attributes, so I left them out.

Feel free to work on this and ask questions here or in the PR you open, I'll be happy to help.

Thanks!
