### ISSUE TITLE
404 error while fetching client roles with name containing special characters (=;+)

### ISSUE THREAD

**Issue by cthiebault** [mrparkers/terraform-provider-keycloak#205]
My role is named `foo=bar;AA;BB/CC+DD`.
I can create it using Terraform but I get following error when assigning this role to group:
`Error: error sending GET request to /auth/admin/realms/myrealm/clients/xxx/roles/foo=bar;AA;BB/CC+DD: 404 Not Found`

It seems related to https://github.com/mrparkers/terraform-provider-keycloak/issues/176 but with more characters than `/`.

**Comment by mrparkers** [comment]
Hmm, I presume that the provider will have to URI encode roles before searching for them using the Keycloak API.
