### ISSUE TITLE
Possibility to change internal openid clients

### ISSUE THREAD

**Issue by Pinguwien** [mrparkers/terraform-provider-keycloak#212]
HI, i tried to disable the realm-internal account-console for a realm created via the tf provider. Now my validation step shows me this:

```
Terraform will perform the following actions:
   # keycloak_openid_client.account will be created
   + resource "keycloak_openid_client" "account" {
       + access_type                  = "CONFIDENTIAL"
       + client_id                    = "account"
       + client_secret                = (sensitive value)
       + direct_access_grants_enabled = false
       + enabled                      = true
       + id                           = (known after apply)
       + implicit_flow_enabled        = false
       + realm_id                     = "myrealm"
       + resource_server_id           = (known after apply)
       + service_account_user_id      = (known after apply)
       + service_accounts_enabled     = false
       + standard_flow_enabled        = false
     }
```

the script I use looks like this:

```
resource "keycloak_openid_client" "account" {
  client_id = "account"
  realm_id = "myrealm"
  enabled = true
  access_type = "CONFIDENTIAL"
}
```

So now I think a new "account" client would be created instead of the existing one (generated by keycloak) would be updated, not? Do I miss something here to get an update instead of the creation of a new one?

Thanks in advance,
Dominik

**Comment by adresan** [comment]
Terraform does only manage resources which belongs to your statefile.

When you create a new realm named myrealm, only the `keycloak_realm.myrealm` resource is managed inside your statefile at this moment. All the default clients are created by keycloak itself and not by terraform, so this clients are not a part of your terraform statefile at this moment and terraform does not know this clients. 

If you declare `resource "keycloak_openid_client" "account" ` and fire a terraform apply, terraform first take a look at your statefile and does not see any managed `keycloak_openid_client.account`  resource and try to provision it via REST. But a client with a unique id `account` alredy exists and your keycloak reject your client creation.

If you want to mange the account client from myrealm, you have to first import the account client resource in your statefile. You can do that by the `terraform import` statement which imports a resource in your statefile and map it to the naming of the resource inside your terraform code. For example:

terraform import keycloak_openid_client.openid_client._account_ _myrealm_/_your-account-client-id_`
`
The account client id could be found in the url when you open your client in your browser. 

In general you can always check the provider documentation. The import statement for a resource is always at the end of the documentation page. https://mrparkers.github.io/terraform-provider-keycloak/resources/keycloak_openid_client/#import

**Comment by mrparkers** [comment]
The answer above describes the problem perfectly.  Unfortunately, Keycloak likes to create a lot of resources for you as a side-effect, so it is difficult to fully manage in code due to situations like this.

I'm going to close this for now, feel free to post here again if you still have more questions.
