### ISSUE TITLE
Refresh of client_default_scopes fails for deleted client

### ISSUE THREAD

**Issue by lathspell** [mrparkers/terraform-provider-keycloak#226]
I successfully applied a Keycloak config and then used the Admin GUI to delete a client.
Afterwards "terraform refresh" and "terraform plan" crashed:

```
$ terraform refresh
keycloak_realm.srt: Refreshing state... [id=srt-test]
keycloak_user.bodo: Refreshing state... [id=410848c9-1fa1-4145-ae81-fe4764294dc2]
keycloak_ldap_user_federation.ldap_user_federation: Refreshing state... [id=e152bc57-17b4-4c6e-a920-3e080704357c]
keycloak_openid_client_scope.srt: Refreshing state... [id=191ac821-d484-4247-abfa-0b76b285b8c3]
keycloak_openid_client.demoapp: Refreshing state... [id=20ade26b-54ad-4aa9-b873-b169270155e3]
keycloak_generic_client_protocol_mapper.obi_srt_realmroles_mapper: Refreshing state... [id=3d14a1bf-1444-4231-a44d-2d0545daaf7d]
keycloak_openid_client_default_scopes.client_default_scopes: Refreshing state... [id=srt-test/20ade26b-54ad-4aa9-b873-b169270155e3]

Error: error sending GET request to /auth/admin/realms/srt-test/clients/20ade26b-54ad-4aa9-b873-b169270155e3/default-client-scopes: 404 Not Found
```

The client "demoapp" (id=20ade26b-54ad-4aa9-b873-b169270155e3) is no longer present which should have been detected in the "keycloak_openid_client.demoapp" block. Still in the keycloak_openid_client_default_scopes" block its Id is used for a GET request.

**Comment by mrparkers** [comment]
This one is a bit tricky.  Normally, resources can detect when they have been deleted manually, and a following run of `terraform apply` will recreate the resource that was deleted manually.

In this case, the `keycloak_openid_client_default_scopes` resource can only function if there is a `keycloak_openid_client` resource that it can reference.  There's no way to recreate this without the client that was deleted.

Your best bet in this case is to run `terraform state rm keycloak_openid_client_default_scopes.client_default_scopes`, and delete them from your HCL code.  There's no way for the provider to recover from this without some manual intervention.

Hope this helps!

**Comment by lathspell** [comment]
Please have a look at https://github.com/mrparkers/terraform-provider-keycloak/pull/252
