### ISSUE TITLE
keycloak_openid_client is missing "Root URL"

### ISSUE THREAD

**Issue by lathspell** [mrparkers/terraform-provider-keycloak#236]
The keycloak_openid_client resource is missing the following two attributes that can be set using the GUI:

* Root URL
See "rootUrl" in https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_clientrepresentation 

* Advanced Settings / Access Token Lifespan
Transmitted as "access.token.lifespan" inside the "attributes" map from  https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_clientrepresentation
The attributes array should maybe provided anyway to allow for arbitrary "advanced" options.

**Comment by lathspell** [comment]
Oh, someone reported the second point already in #232!

**Comment by tomrutsaert** [comment]
root_url support was added in #248
