### ISSUE TITLE
keycloak_realm is missing defaultSignatureAlgorithm

### ISSUE THREAD

**Issue by lathspell** [mrparkers/terraform-provider-keycloak#238]
They keycloak_realm resource is missing the attribute "defaultSignatureAlgorithm" from https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_realmrepresentation that is needed to change the Algo from HS256 to RS256 as some framekworks like Micronaut do not understand HS256 (at least in the version I've encountered).

**Comment by lathspell** [comment]
This issue can probably be closed as you merged https://github.com/mrparkers/terraform-provider-keycloak/pull/282 in June?

**Comment by mrparkers** [comment]
You're correct, thanks for helping me clean up :smile:
