### ISSUE TITLE
Javascript or Drools policies?

### ISSUE THREAD

**Issue by oreza** [mrparkers/terraform-provider-keycloak#245]
Hi,
Can we use this provider to setup client resources and associated, permissions and javascript policies policies or drools policies?
Thanks

**Comment by mrparkers** [comment]
I think what you're looking for is currently being worked on in #246.  Can you let me know if the contents of that PR will help you?

**Comment by mrparkers** [comment]
I'm gonna close this since #246 has been merged and a release has been cut.  Let me know if this doesn't cover what you're looking for and I can re-open this.

**Comment by oreza** [comment]
Hi Parker,
Sorry for late reply, due to Cronovirus we had some changes in our schedules. We are not using Drools anymore, since it  is been deprecated, I think only requirements we had is to use Javascript policies. I will give it spin, as soon as possible.
