### ISSUE TITLE
keycloak_user is missing "attributes"

### ISSUE THREAD

**Issue by lathspell** [mrparkers/terraform-provider-keycloak#257]
The `keycloak_user` element is missing the "Attributes" key-value-map that is available in the GUI.

See https://mrparkers.github.io/terraform-provider-keycloak/resources/keycloak_user/ and
https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_userrepresentation where "attributes" is listed.

I understand that local users are generally not recommended but for instances with <10 users or test setups in stages where the LDAP server is unavailable etc it's nice to quickly create some fake users. They often do require some attributes though to look the same as a user coming from LDAP/SQL.

**Comment by radekg** [comment]
Hey @mrparkers, thank you for this provider. I have been looking through the issues and have noticed that the attributes appear to be on the master branch: https://github.com/mrparkers/terraform-provider-keycloak/commit/1267c01c079159818d5f7820a6a16baf3034a173#diff-67e0a793fd292094547b9fe88008a2d6.

**Comment by mrparkers** [comment]
You're right, it looks like this feature does exist, but is unfortunately missing from the docs.  I haven't been doing a great job keeping the docs fully up to date, my apologies.

I'll go ahead and close this and get the docs updated.
