### ISSUE TITLE
Support for SAML Role Name Mapper

### ISSUE THREAD

**Issue by mechastorm** [mrparkers/terraform-provider-keycloak#273]
It would be good if this Terraform provider supported the ability for Keycloak to map role names in the SAML client.

In the Keycloak REST API docs, this is the "Protocol Mappers" > "Create a mapper"
https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_protocol_mappers_resource

Example POST URL
```
https://<keycloak domain>/auth/admin/realms/<keycloak realm>/clients/<keycloak_client_id>/protocol-mappers/models
```

Example POST payload
```
{
	"protocol": "saml",
	"config": {
		"role": "<my-client-alias>.<my-client-role-name>",
		"new.role.name": "<aws iam role arn>,<aws saml identity provider arn>"
	},
	"name": "my-client-role-name",
	"protocolMapper": "saml-role-name-mapper"
}
```

In my use case, I am configuring Keycloak for AWS SAML SSO. 

- AWS Docs states that it needs the role names to be `<aws_role_arn>,<aws_saml_identity_provider_arn>` in that exact format - even with the special characters (ie. `:`, `,`)
- Recent update to Keycloak (I am using `v9.2`) has now disallowed special characters in a Keycloak Role
- The current work around is to set up a "Role name mapper" in the SAML client

I reporting this as a new feature suggestion for this provider to support. I may try to deal with it but I am still quite a newbie to both Golang and Terraform Provider development. I will update this issue if I end up doing a PR of my own if no one decided to tackle this yet.

**Comment by ryanmac8** [comment]
@mechastorm It's actually already supported. Use the generic client protocol mapper. Also you can view the source page in Chrome and see what config is expected when using the generic client protocol mapper.

resource "keycloak_generic_client_protocol_mapper" "saml-role-mapping" {
  realm_id        = "master"
  client_id       = keycloak_saml_client.saml_client.id
  name            = "Role Name Mapping"
  protocol        = "saml"
  protocol_mapper = "saml-role-name-mapper"
  config = {
    "role"          = "<Old Role Name Here>"
    "new.role.name" = "<ARN HERE>"
  }
}

**Comment by mechastorm** [comment]
Thank you @ryanmac8 ! That worked as intended.

As such this issue can be closed as the need for a dedicated resource just for SAML Role Name Mapper is merely a convenience than a necessity.

My implementation

```hcl
resource "keycloak_generic_client_protocol_mapper" "aws-role" {
  realm_id        = var.keycloak_realm_alias
  client_id       = var.keycloak_aws_client_id
  name            = <name of the mapper>
  protocol        = "saml"
  protocol_mapper = "saml-role-name-mapper"
  config = {
    "role"          = "<my-client-alias>.<my-client-role-name>"
    "new.role.name" = "<aws iam role arn>,<aws saml identity provider arn>"
  }
}
```

In addition if one was to use Keycloak 10.0.2 and above, the support for special characters in role name has been re-enabled again - so the workaround with a role name mapper is no longer required.
