### ISSUE TITLE
PR #272 breaks refresh of existing state

### ISSUE THREAD

**Issue by dmeyerholt** [mrparkers/terraform-provider-keycloak#283]
Hi,
during testing the current master tree' terraform refresh on a rather large state, it aborted with several
`Error: strconv.ParseBool: parsing "": invalid syntax`
errors. This seems to be related to PR #272 and commit 2bf367a0d330fe169511c53a4c1fff70e6a0d072 . maybe specifically this line https://github.com/mrparkers/terraform-provider-keycloak/blob/2bf367a0d330fe169511c53a4c1fff70e6a0d072/keycloak/openid_user_attribute_protocol_mapper.go#L68 ?  reverting this locally makes everything good again. somebody else have the same issue or am I missing something here?
Our installation: Keycloak 6.0.1 , provider: current master

Best

**Comment by mrparkers** [comment]
Hey @dmeyerholt, sorry that this is happening to you.

I tried to reproduce this by running Keycloak 6.0.1 and applying the configuration in `example/main.tf` which includes a few of the resources that appear to be causing you problems, and I wasn't able to reproduce it.

Could you help me out by providing some sample HCL that reproduces this?

**Comment by mrparkers** [comment]
Nevermind, I was able to reproduce it.  I can work on a fix, thanks for the bug report!

**Comment by mrparkers** [comment]
@dmeyerholt let me know if the current master branch fixed your issue.  If it doesn't, feel free to reopen this.

**Comment by dmeyerholt** [comment]
Everything is fine now, thanks for the quick fix
