### ISSUE TITLE
How to update built-in resources, like Master Realm?

### ISSUE THREAD

**Issue by rdelander** [mrparkers/terraform-provider-keycloak#288]
Is it possible to update resources that are created by default?  To be clear, I am using the public docker image like so: `docker run -p 8080:8080 jboss/keycloak`

My goal is to update the theme attributes for the master realm.  I can query for the realm, but my understanding is that there is no way to then update it.
```
data "keycloak_realm" "master_realm" {
  realm = "master"
}
```

Clearly I will get conflict errors when trying to setup an additional `master` realm resource like so:
```
resource "keycloak_realm" "master_realm" {
  realm = data.keycloak_realm.master_realm.realm
  login_theme = "example"
}
```

My apologies if there is an obvious solution, this is my first time using Terraform.

**Comment by tomrutsaert** [comment]
You need to do first a _terraform import_ to be able to handle the state of an already existing resource that was not created by terrafrom.
More info can be found here: https://www.terraform.io/docs/import/index.html

On the top of my head you need to do following:

Create a tf file and add an empty master realm resource:

`
resource "keycloak_realm" "master_realm" {
}
`

Then run following command:

`terraform import keycloak_realm.master master`

From that moment you master realm state is managed by terraform and can change the theme attributes

**Comment by rdelander** [comment]
This approach is working for me.  Thank you
