### ISSUE TITLE
Missing SSO session "remember me" realm attributes

### ISSUE THREAD

**Issue by amfl** [mrparkers/terraform-provider-keycloak#289]
There are currently some [sso session expiration attributes](https://github.com/mrparkers/terraform-provider-keycloak/blob/master/docs/resources/keycloak_realm.md#tokens) which can be set on the realm resource.

> * **sso_session_idle_timeout** - (Optional) The amount of time a session can be idle before it expires.
> * **sso_session_max_lifespan** - (Optional) The maximum amount of time before a session expires regardless of activity.

According to the [Keycloak docs](https://www.keycloak.org/docs/latest/server_admin/index.html#_timeouts), there should _also_ be settings specific to the "remember me" switch which appear to be missing from the Terraform provider (Something like `sso_session_idle_timeout_remember_me` and `sso_session_max_lifespan_remember_me`.)

> * **SSO Session Idle Remember Me** - Same as the standard SSO Session Idle configuration but specific to logins  with Remember Me enabled. It allows for the specification of longer session idle timeouts when Remember Me is selected during the login process. It is an optional configuration and if not set to a value greater than 0 it uses the same idle timeout as set in the SSO Session Idle configuration.
> * **SSO Session Max Remember Me** - Same as the standard SSO Session Max but specific to logins with Remember Me  enabled. It allows for the specification of longer lived  sessions when Remember Me is selected during the login process. It is  an optional configuration and if not set to a value greater than 0 it uses the same session lifespan as set in the SSO Session Max configuration.

**Comment by BytewaveMLP** [comment]
Looks like this was closed in #374?

**Comment by amfl** [comment]
Yep :)
