### ISSUE TITLE
Register as thirdparty provider for terraform 0.13 

### ISSUE THREAD

**Issue by cpesch** [mrparkers/terraform-provider-keycloak#313]
When using the latest 1.18.0 plugin with terraform 0.13 beta 1 I failed to get beyond

```
$ terraform init 
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/keycloak versions matching "~> 1.18"...

Error: Failed to install provider

Error while installing hashicorp/keycloak: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/keycloak
```

https://www.hashicorp.com/blog/adding-provider-source-to-hashicorp-terraform/ says

> Authors can host and publish providers to the Registry from their own GitHub repositories.

Please consider this.

**Comment by mrparkers** [comment]
This seems like an awesome change, I'll be looking forward to not having to build my own Docker images with all of my third party providers pre-installed.  Once I learn more about this I'll happily work on it.

**Comment by rdelander** [comment]
Any updates on this?  I am also really looking forward to using the beta for the new modules for_each functionality

**Comment by cpesch** [comment]
Hi @rdelander,

since 0.13 beta 2 it's possible to use module for_each 

I've added a versions.tf to both the module and the project including it:

```
terraform {
  required_providers {
    keycloak = {
      source  = "github.com/mrparker/keycloak"
      version = "1.19.0"
    }
  }
  required_version = ">= 0.13"
}
``` 

After moving the plugin to

`~/.terraform.d/plugins/github.com/mrparker/keycloak/1.19.0/darwin_amd64/terraform-provider-keycloak_v1.19.0
`

it works fine for me without a registration. Which would still be helpful though ;-)

**Comment by rdelander** [comment]
@cpesch I just returned to attempting the move over to 0.13.  Looks like I'm still seeing this error with your approach:
```
Initializing provider plugins...
- Using previously-installed github.com/mrparker/keycloak v1.18.0
- Finding latest version of hashicorp/keycloak...

Error: Failed to install provider

Error while installing hashicorp/keycloak: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/keycloak
```

My setup:
```
terraform {
  required_providers {
    keycloak = {
      source    = "github.com/mrparker/keycloak"
      version   = "1.18.0"
      client_id = "admin-cli"
      username  = "admin"
      password  = "admin"
      url       = "http://localhost:8080"
    }
  }
  required_version = ">= 0.13"
}
```
I also moved the plug to 
```
~/.terraform.d/plugins/github.com/mrparker/keycloak/1.18.0/darwin_amd64/terraform-provider-keycloak_v1.18.0
```

Was wondering if you had any other advice?  Thanks for the help.

**Comment by cpesch** [comment]
Please follow https://www.terraform.io/docs/internals/debugging.html and try to set TF_LOG=TRACE and have a look a the output

**Comment by cah-andrew-fitzgerald** [comment]
@rdelander I think you actually want to remove the `required_providers` block and just use `provider keycloak` as top level configuration until this issue is complete.

My understanding is that the `terraform.required_providers` block is for pulling providers from the registry.
Since this one isn't in the registry yet, you shouldn't be using it.

**Comment by mrparkers** [comment]
Just wanted to update everyone here that I'll be working on getting this provider added to the Terraform registry this week.  There's a lot of work to update the documentation and add some stuff to the release process.

**Comment by mrparkers** [comment]
Update - I'm about halfway done with fixing the documentation (also taking the time to backfill missing docs).

**Comment by mrparkers** [comment]
Update - the pre-release tag `v2.0.0-rc.0` has been published to the Terraform Registry: https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs

You can try it out with Terraform 0.13 using the `terraform` block:

```hcl
terraform {
  required_providers {
    keycloak = {
      source = "mrparkers/keycloak"
      version = "2.0.0-rc.0"
    }
  }
}
```

The stable version (`v2.0.0`) along with changelog notes will be published some time next week, after I've had some time to use it and test it out personally.

Note: the reason for the breaking change from 1 -> 2 is due to an upgrade to `terraform-plugin-sdk@v2`. This means that this provider [will no longer work with Terraform 0.11](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#dropped-support-for-terraform-0-11-and-below).

Please use this thread to report any issues you have with this pre-release instead of opening a new issue.  Thanks!

**Comment by svenstaro** [comment]
Ok, this works great for me. I first had to change the provider in my state because otherwise, Terraform would be unhappy because it couldn't get the implicit `-/keycloak` (which is the automatic legacy name) to map to `mrparkers/keycloak`.
So doing

    terraform state replace-provider registry.terraform.io/-/keycloak mrparkers/keycloak

and then

    terraform init

works absolutely fine and results in expected working stuff.

**Comment by cthiebault** [comment]
I've followed previous steps...

Running `terraform providers` returns:
```
Providers required by configuration:
.
├── provider[registry.terraform.io/mrparkers/keycloak] 2.0.0-rc.0
├── provider[registry.terraform.io/hashicorp/aws] 3.4.0
└── module.keycloak
    └── provider[registry.terraform.io/hashicorp/keycloak]

Providers required by state:

    provider[registry.terraform.io/mrparkers/keycloak]

    provider[registry.terraform.io/hashicorp/aws]
```

But when running `terraform init`, I get:
```
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed mrparkers/keycloak v2.0.0-rc.0
- Using previously-installed hashicorp/aws v3.4.0
- Finding latest version of hashicorp/keycloak...

Error: Failed to install provider

Error while installing hashicorp/keycloak: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/keycloak
```

Any idea?

**Comment by svenstaro** [comment]
@cthiebault did you do the `provider-replace` thing I mentioned in my post? You should replace `registry.terraform.io/hashicorp/keycloak` with `mrparkers/keycloak`.

**Comment by pascal-hofmann** [comment]
@cthiebault 
Try with this instead:
```terraform state replace-provider registry.terraform.io/-/keycloak mrparkers/keycloak```

**Comment by cthiebault** [comment]
@pascal-hofmann same response:
```
> terraform state replace-provider registry.terraform.io/-/keycloak mrparkers/keycloak                                                                                             No matching resources found.
```

**Comment by pascal-hofmann** [comment]
Ah. Now I spotted the issue: 

```
└── module.keycloak
    └── provider[registry.terraform.io/hashicorp/keycloak]
```

This module still wants to have `hashicorp/keycloak`

**Comment by cthiebault** [comment]
@pascal-hofmann and how can I replace module's providers?

**Comment by pascal-hofmann** [comment]
> @pascal-hofmann and how can I replace module's providers?

AFAIK the module itself must be changed. You must add the following there too:
```
required_providers {
    keycloak = {
      source  = "mrparkers/keycloak"
      version = "2.0.0-rc.0"
    }
}
```

**Comment by cthiebault** [comment]
It works now :-)
I didn't we had to configure `required_providers` for modules...

Thanks for your help @pascal-hofmann !!

**Comment by DOboznyi** [comment]
@mrparkers will you create a release 2.0.0?

**Comment by mrparkers** [comment]
v2.0.0 has been published, thanks for your patience everyone!

**Comment by AsheAustaire** [comment]
> required_providers

Can you please elaborate?
