### ISSUE TITLE
An argument named "default_scopes" is not expected here.

### ISSUE THREAD

**Issue by mattronix** [mrparkers/terraform-provider-keycloak#317]
Get the following error when using below config "An argument named "default_scopes" is not expected here."
resource "keycloak_oidc_identity_provider" "REMOVED" {
  realm             = "master"
  alias             = "REMOVED"
  display_name      = "REMOVED"
  authorization_url = "REMOVED"
  client_id         = "REMOVED"
  client_secret     = "REMOVED" 
  token_url         = "REMOVED"
  logout_url        = "REMOVED"
  user_info_url     = "REMOVED"
  default_scopes  = "openid profile email"
  extra_config = {
    "clientAuthMethod"  = "client_secret_post"
    
  }
  
}

**Comment by mattronix** [comment]
Wondering if i might be doing something wrong :)

**Comment by mattronix** [comment]
default_scopes - (Optional) The scopes to be sent when asking for authorization. It can be a space-separated list of scopes. Defaults to 'openid'.

**Comment by tomrutsaert** [comment]
Should normally work

What version of keycloak and what version of the provider are you using?

**Comment by mattronix** [comment]
* provider.keycloak: version = "~> 1.16"

**Comment by mattronix** [comment]
Keycloak version: 8.0.1

**Comment by mattronix** [comment]
I'm using the provider from the registry so guessing that maybe the problem?

**Comment by mattronix** [comment]
I have found the issue seems this machine im on had keycloak provider installed already from an older release thought it came from the registry. 

WIll update and try again.

**Comment by mattronix** [comment]
Fixed!

**Comment by mattronix** [comment]
Thanks! :)
