### ISSUE TITLE
Offline Session Max Limited toggle

### ISSUE THREAD

**Issue by alialperak** [mrparkers/terraform-provider-keycloak#322]
Setting `offline_session_max_lifespan` in `keycloak_realm` requires setting `Offline Session Max Limited` to `true` to work. Currently there is no way to set `Offline Session Max Limited` in the provider.

Testing on keycloak version: 8.0.1

**Comment by lawrenceong** [comment]
There is a separate problem to it.  Manually setting offline session max limited toggle to enabled and running against the realm will toggle it back to false if there is a change to the realm config.
