### ISSUE TITLE
Unable to retrieve keycloak_user resource's username property

### ISSUE THREAD

**Issue by n0rig** [mrparkers/terraform-provider-keycloak#323]
I was trying to pass a list of emails to a group membership by using their respective keycloak_users resource; as shown here:
https://github.com/mrparkers/terraform-provider-keycloak/blob/213ec9ac4260562c739f669caea4120704f80b1f/example/main.tf#L142

However, this does not work for me on v1.19 of the keycloak provider.

error:
```bash
Error: Reference to undeclared output value

  on product_role_Developer.tf line 10, in module "role_Developer":
  10:     module.users.keycloak_user.user["user1@example.com"]

An output value with the name "keycloak_user" has not been declared in
module.users.
```

**Comment by mrparkers** [comment]
This does not look like a provider issue to me.  It looks like you have a terraform module called `users`, and you're trying to use an output from this module called `keycloak_user`, and the error message you're receiving is that the module `users` does not have an output called `keycloak_user`.

In other words, I'd expect to see something like this in your module:

```hcl
output "keycloak_user" {
   value = "foo"
}
```

Let me know if adding this output helps with the error you're receiving.

**Comment by mrparkers** [comment]
I'm going to go ahead and close this since it doesn't look like a provider issue.  Feel free to re-open this if you still have more questions.
