### ISSUE TITLE
Custom terms.ftl for Terms and Conditions in login theme

### ISSUE THREAD

**Issue by timbmg** [mrparkers/terraform-provider-keycloak#326]
Is there a way to update the `terms.ftl` of the login_theme?

**Comment by tomrutsaert** [comment]
No, This provider is to configure keycloak, not to extend keycloak.
You need to create a custom theme for this.
The easiest way, is to extend the existing keycloak login theme and override terms.ftl, or set the correct message in message.properties.
More information can be found in the keycloak documentation.
https://www.keycloak.org/docs/latest/server_development/index.html#_themes
Once the custom theme is added to your keycloak instance, you can set through this provider
