### ISSUE TITLE
Question: how to create service account "realm admin" role?

### ISSUE THREAD

**Issue by shaunc** [mrparkers/terraform-provider-keycloak#328]
[From the docs:](https://mrparkers.github.io/terraform-provider-keycloak/#assigning-roles)

> Managing the entire foo realm: Assign the realm-admin client role from the realm-management client to a user or service account within the foo realm.

I'm programmatically creating a realm, and want to add a "terraform" client for subsequent management. How do I do what the docs ask me to do?

**Comment by tomrutsaert** [comment]
I think this was already answered in #329,
I will close this, If needed you can reopen it.

**Comment by shaunc** [comment]
Ah -- sorry -- didn't mean to duplicate; not sure how that happened.
