### ISSUE TITLE
Question: how to add roles to a service account?

### ISSUE THREAD

**Issue by shaunc** [mrparkers/terraform-provider-keycloak#329]
[From the docs:](https://mrparkers.github.io/terraform-provider-keycloak/#assigning-roles)

> Managing the entire foo realm: Assign the realm-admin client role from the realm-management client to a user or service account within the foo realm.

I'm programmatically creating a realm, and want to add a "terraform" client for subsequent infrastructure management by terraform. How do I do what the docs ask me to do?

**Comment by tomrutsaert** [comment]
In what language or script-language do you want to create this 'terraform' client?

In bash you could use this script:

https://github.com/mrparkers/terraform-provider-keycloak/blob/master/scripts/create-terraform-client.sh

**Comment by shaunc** [comment]
@tomrutsaert Ah -- thanks for the link! I was hoping to create in terraform, but it would seem that the package doesn't support assigning roles? (Sorry -- I'm a newbie with this provider.) The script is a good plan B.

**Comment by tomrutsaert** [comment]
well it does, but you first need to have a user/client that can execute the necessary api calls so that the provider will be able to do these same api calls....
That is why the documentation talks about having user/client with a realm-admin role to be able to manage the specified realm..... 
It is a bit chicken/egg problem. You can not use this keycloak-terraform-provider to manage keycloak instance if the keycloak-terraform-provider does not have the correct rights/permissions to do so.
So this keycloak-terraform-provider needs some-how to have these permissions/rights, and once it has i , it can manage all others things through that permission/right.
This could also be the master realm admin credentials, you set when creating a new keycloak instance.
But this all really depends on your specific situation....

(i hope this is not a too confusing comment)

**Comment by shaunc** [comment]
The situation is this: In terraform provider #1 I am using default admin client w/ password to create realm, and add "terraform" client. Then #2 to setup particular clients in that realm I have another terraform provider which uses it to create. 

In #1 the step I can't yet do is add the role to the service account of the "terraform" client.

**Comment by tomrutsaert** [comment]
in step 1 you could add something like this:


```
resource "keycloak_realm" "my-realm" {
    realm   = "my-realm"
    enabled = true
}

data "keycloak_role" "my-realm_admin_role" {
    realm_id = keycloak_realm.my-realm.id
    name     = "admin"
}

resource "keycloak_openid_client" "my-realm_terraform_client" {
  realm_id                     = keycloak_realm.my-realm.id
  name                         = "terraform_client"
  client_id                    = "terraform_client"
  client_secret                = "secret"
  access_type                  = "CONFIDENTIAL"
  service_accounts_enabled     = true
}

resource "keycloak_openid_client_service_account_role" "terraform_client_sa_role_mapping" {
  realm_id                = keycloak_realm.my-realm.id
  client_id               = keycloak_openid_client.my-realm_terraform_client.id
  service_account_user_id = keycloak_openid_client.my-realm_terraform_client.service_account_user_id
  role                    = data.keycloak_role.my-realm_admin_role.name
}
```

I just typed this, I did not test this, so there could be a mistake in it, but it should give you a general idea....

**Comment by shaunc** [comment]
Aha -- `terraform_client_sa_role_mapping` -- that was exactly the part I was missing! :)

I was confused -- I thought that the "mapping" was for client "mappers." I need to get my head around the keycloak data model a bit more. Thank you! ... (I'll go try and close if it works :))

**Comment by shaunc** [comment]
Hmm.. so the role I want to assign is the "client role" of "realm-admin" from the "realm-management" client. Can I get ahold of this using a data.keycloak_role?

![image](https://user-images.githubusercontent.com/193170/85742486-46c5a700-b6d1-11ea-8aca-51aeb5f25e24.png)

**Comment by shaunc** [comment]
Hmm... for `role` in `keycloak_openid_client_service_account_realm_role` I tried `data.keycloak_role.my-realm_admin_role.name` as you suggested, and also `data.keycloak_role.my-realm_admin_role.id`. Either way I get: "Role not found".

Where is the documentation to `keycloak_openid_client_service_account_realm_role`?

---
```
  # keycloak_openid_client_service_account_realm_role.terraform_client_sa_role_mapping will be created
  + resource "keycloak_openid_client_service_account_realm_role" "terraform_client_sa_role_mapping" {
      + id                      = (known after apply)
      + realm_id                = "factfiber"
      + role                    = "91b..."
      + service_account_user_id = "661..."
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

keycloak_openid_client_service_account_realm_role.terraform_client_sa_role_mapping: Creating...

Error: error sending POST request to /auth/admin/realms/factfiber/users/6618.../role-mappings/realm: 404 Not Found. Response body: {"error":"Role not found"}

  on main.tf line 92, in resource "keycloak_openid_client_service_account_realm_role" "terraform_client_sa_role_mapping":
  92: resource keycloak_openid_client_service_account_realm_role terraform_client_sa_role_mapping {

```

**Comment by tomrutsaert** [comment]
The docs are missing, 

client role can be done via

```
resource "keycloak_openid_client_service_account_role" "terraform_client_sa_role_mapping" {
  realm_id                = keycloak_realm.my-realm.id
  client_id               = keycloak_openid_client.my-realm_terraform_client.id
  service_account_user_id = keycloak_openid_client.my-realm_terraform_client.service_account_user_id
  role                    = "clientrole"
}
```

**Comment by shaunc** [comment]
Great! So for the record, this is what works:
```
resource keycloak_openid_client admin_client {
  realm_id = keycloak_realm.factfiber.id
  client_id = "terraform"
  access_type = "CONFIDENTIAL"
  client_secret = local.client_secret
  standard_flow_enabled = false
  direct_access_grants_enabled = false
  # use api via token, rather than grant access
  service_accounts_enabled = true
  description = "Client for programmatic realm management"
}

data keycloak_openid_client realm_management {
  realm_id = keycloak_realm.factfiber.id
  client_id = "realm-management"
}

data keycloak_role factfiber_realm_admin_role {
  realm_id = keycloak_realm.factfiber.id
  client_id = data.keycloak_openid_client.realm_management.id
  name     = "realm-admin"
}

resource keycloak_openid_client_service_account_role terraform_client_sa_role_mapping {
  realm_id = keycloak_realm.factfiber.id
  service_account_user_id = keycloak_openid_client.admin_client.service_account_user_id
  client_id = data.keycloak_openid_client.realm_management.id
  role                    = data.keycloak_role.factfiber_realm_admin_role.name
}
```
Also, it would seem that the doc is on its way already, just not up on the docs site: https://github.com/mrparkers/terraform-provider-keycloak/blob/master/docs/resources/keycloak_openid_client_service_account_role.md

Thank you so much for your help!

**Comment by mrparkers** [comment]
> Also, it would seem that the doc is on its way already, just not up on the docs site

Thanks for pointing that out, it should be live on the docs site in a few minutes.
