### ISSUE TITLE
Relative base_urls are marked as invalid inputs (1.16.0 -> 1.19.0)

### ISSUE THREAD

**Issue by ghost** [mrparkers/terraform-provider-keycloak#343]
Good morning,

when creating a new realm, keycloak adding some standard clients (account, account-console, security-admin-console). This clients using relative urls as the base url. If i import this client to manage it in terraform also, i could use the relative url in version 1.16.0. For example:

`base_url = "/realms/myrealm/account/"`

![image](https://user-images.githubusercontent.com/68268916/87395339-7d486080-c5b1-11ea-8acc-707ede5086ce.png)

Keycloak complete this url as a full url in the client overview automatically:

![image](https://user-images.githubusercontent.com/68268916/87395455-b5e83a00-c5b1-11ea-83fa-570cfb886964.png)

when i update the provider to version 1.19.0, the relative url is marked as a invalid url.

`Error: error sending PUT request to //auth/admin/realms/myrealm/clients/3d3123d8-583d-4c34-b195-f0d9a1628043: 400 Bad Request. Response body: {"error":"invalid_input","error_description":"Invalid URL in baseUrl"}`

I think this is a bug and the provider should accept relative urls again.

best regards

**Comment by mrparkers** [comment]
Hi @anepak,

I believe I was able to fix this in #344.  I think it's a Keycloak API issue, where the API rejects the request if it includes an empty `rootUrl` (even if the `rootUrl` for the client is already empty).

If you can, I'd appreciate it if you'd build the provider from source with the contents of #344 and give it a shot to see if it fixes the issue you were having.

**Comment by anepak** [comment]
@mrparkers Thanks for the quick fix and your reply. I will build the provider and test it. I give you a feedback tomorrow.

**Comment by anepak** [comment]
@mrparkers iam sorry to tell that the code from #344  does not fix the issue.

**Comment by mrparkers** [comment]
Could you give me a sample HCL snippet that reproduces the issue you're seeing?  It's possible that the same conflict I fixed in #344 exists for other attributes as well.  Thanks!

**Comment by anepak** [comment]
@mrparkers Thanks for your reply

i can reproduce it this way:

1. Create a new realm via `terraform apply`

```
resource "keycloak_realm" "myrealm" {
  realm        = "myrealm"   # Name
  enabled      = true        # Enabled
  display_name = "mymyrealm" # Display Name
}
```

2. Define the account client of this realm

```
resource "keycloak_openid_client" "account" {
  realm_id                     = keycloak_realm.myrealm.id
  client_id                    = "account"
  base_url                     = "/realms/myrealm/account/"
  name                         = "$${client_account}"
  description                  = ""
  enabled                      = true
  access_type                  = "CONFIDENTIAL"
  standard_flow_enabled        = true
  implicit_flow_enabled        = false
  direct_access_grants_enabled = false
  service_accounts_enabled     = false
  valid_redirect_uris          = ["/realms/myrealm/account/*"]
  web_origins                  = [""]
  full_scope_allowed           = false
}
```
3. Import the account client to the statefile

`terraform import keycloak_openid_client.account myrealm/{id}`

4. Trigger a `terraform apply`

Then it shows the following output:

                                                           
> keycloak_realm.myrealm: Refreshing state... [id=myrealm]
> keycloak_openid_client.account: Refreshing state... [id=d90f0410-1201-4485-ae0c-75780711d482]
> 
> An execution plan has been generated and is shown below.
> Resource actions are indicated with the following symbols:
>   ~ update in-place
> 
> Terraform will perform the following actions:
> 
>   # keycloak_openid_client.account will be updated in-place
>   ~ resource "keycloak_openid_client" "account" {
>         access_type                              = "CONFIDENTIAL"
>         base_url                                 = "/realms/myrealm/account/"
>         client_id                                = "account"
>         client_secret                            = (sensitive value)
>         consent_required                         = false
>         direct_access_grants_enabled             = false
>         enabled                                  = true
>       + exclude_session_state_from_auth_response = false
>         full_scope_allowed                       = false
>         id                                       = "d90f0410-1201-4485-ae0c-75780711d482"
>         implicit_flow_enabled                    = false
>         name                                     = "${client_account}"
>         realm_id                                 = "myrealm"
>       - root_url                                 = "${authBaseUrl}" -> null
>         service_accounts_enabled                 = false
>         standard_flow_enabled                    = true
>         valid_redirect_uris                      = [
>             "/realms/myrealm/account/*",
>         ]
>       ~ web_origins                              = [
>           + "",
>         ]
>     }
> 
> Plan: 0 to add, 1 to change, 0 to destroy.
> 
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> keycloak_openid_client.account: Modifying... [id=d90f0410-1201-4485-ae0c-75780711d482]
> 
> Error: error sending PUT request to //auth/admin/realms/myrealm/clients/d90f0410-1201-4485-ae0c-75780711d482: 400 Bad Request. Response body: {"error":"invalid_input","error_description":"Invalid URL in baseUrl"}
> 
>   on main.tf line 24, in resource "keycloak_openid_client" "account":
>   24: resource "keycloak_openid_client" "account" {
>

**Comment by mrparkers** [comment]
this seems to no longer be an issue on v2.1.0 of the provider.  I tested your example against keycloak 12 and it seems to be working.  if this is still an issue, feel free to comment again and I'll reopen this.
