### ISSUE TITLE
Documentation is not updated for version 1.20

### ISSUE THREAD

**Issue by tomrutsaert** [mrparkers/terraform-provider-keycloak#349]
@mrparkers could it be that the documentation is not updated to the latest release version?
For example, I do not find the keycloak_identity_provider_token_exchange_scope_permission documentation part.
Can I upgrade the documentation myself? If yes,how?

**Comment by mrparkers** [comment]
You're right, I forgot to do this.  Just updated it now.

I use `mkdocs gh-deploy` to update the docs, which requires push access to the `gh-pages` branch, which you should have.  So you can do this in the future if you want.

I really need to bake this into the CI process for releasing so this doesn't need to be a manual process.

Thanks for the reminder!
