### ISSUE TITLE
Realm field "registration_flow" missing from the docs

### ISSUE THREAD

**Issue by Kinrany** [mrparkers/terraform-provider-keycloak#370]
`registration_flow` can be specified, and is recognized by the Terraform plugin for VSCode, but is never mentioned in the docs.

**Comment by Kinrany** [comment]
It's already there in [the master branch](https://github.com/mrparkers/terraform-provider-keycloak/blob/master/docs/resources/realm.md), but not in [the docs](https://mrparkers.github.io/terraform-provider-keycloak/resources/keycloak_realm/)

**Comment by mrparkers** [comment]
Hi @Kinrany, thanks for the issue.  This is available in the new docs located here: https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/realm#registration_flow

Once I cut a release next week, all of the links will be updated to the new docs.
