### ISSUE TITLE
Add keycloak_openid_generic_mapper to support custom identity mappers

### ISSUE THREAD

**Issue by hamiltont** [mrparkers/terraform-provider-keycloak#382]
Currently custom identity broker mappings cannot be configured through this project. 

By adding a generic option, similar to the `keycloak_generic_client_protocol_mapper`, we could allow for custom mappers to be configured & managed through this provider

For context, the runtime (non-compiled) configuration is based on the [ProviderConfigProperty](https://github.com/keycloak/keycloak/blob/master/server-spi/src/main/java/org/keycloak/provider/ProviderConfigProperty.java), which puts a nice restriction the the types of configuration keys (strings, lists, etc). 

Also for context, here is the [Model class](https://github.com/keycloak/keycloak/blob/master/server-spi/src/main/java/org/keycloak/models/IdentityProviderMapperModel.java) 

I'm not familiar enough with SAML to know if a `keycloak_generic_identity_broker_mapper` would make more sense, where the user selects SAML or OIDC as a config value

**Comment by hamiltont** [comment]
FYI - Added a $200 bounty [over on bountysource](https://www.bountysource.com/issues/92864362-add-keycloak_openid_generic_mapper-to-support-custom-identity-mappers) because I could use this feature but sadly don't have time right now to implement it myself

**Comment by tomrutsaert** [comment]
If i am understanding it correctly, I think it already exists

https://mrparkers.github.io/terraform-provider-keycloak/resources/keycloak_attribute_importer_identity_provider_mapper/

Have fun, keep the money,
Reinvest into the project when you have some more time.

Let me know if that is not what you are searching for

**Comment by hamiltont** [comment]
@tomrutsaert thanks for the reply! As far as I can tell, that's not the same thing. The "Attribute Importer" is one specific type of Identity Provider Mapper in KeyCloak. There are 4-5 of these predefined ones. Note the confusing terminology of "Identity Provider Mappers" (these are distinct from the more common "Client Mappers") in KeyCloak. To see the list of builtin ones, on any KC realm, navigate to `Identity Providers > Select a provider > Mappers > Create`. For what it's worth, I think the Attribute Importer is the only type currently supported by this provider. It would probably be the only example of how to make another one. 

This ticket is about adding a "generic" version that looks like the existing `keycloak_attribute_importer_identity_provider_mapper` but allows passing in arbitrary config items in the same way the `keycloak_generic_client_protocol_mapper` allows

**Comment by tomrutsaert** [comment]
You are right,
You need a small extension on top of the `generic_keycloak_identity_provider_mapper`, that allows to set the `IdentityProviderMapper` field. The code would not be so different as the code of `keycloak_attribute_importer_identity_provider_mapper`. 
Also imho it should support more then just oidc and saml identityProviders.
It should not be too hard to do, But I do not have the time right now....
