### ISSUE TITLE
Setting resource IDs manually

### ISSUE THREAD

**Issue by sj14** [mrparkers/terraform-provider-keycloak#384]
Hello everyone,

is it possible to set ID's, e.g. for the users, manually? In the Keycloak API for the [UserRepresentation](https://www.keycloak.org/docs-api/10.0/rest-api/index.html#_userrepresentation), the ID is an optional field.

When I try setting it in the `keycloak_user` resource manually, I get the following error:

```
Error: Invalid or unknown key

  on ../modules/keycloak/xyz.tf line 134, in resource "keycloak_user" "xyz_users":
 134:   id             = "value"
```

I had a first look into the source code. Unfortunately, adding `id` to the user schema doesn't work. 

```
=== RUN   TestAccKeycloakUser_federatedLink
    resource_keycloak_user_test.go:303: Step 1/2 error: terraform failed: exit status 1
        
        stderr:
        
        Error: InternalValidate
        
        Internal validation of the provider failed! This is always a bug
        with the provider itself, and not a user issue. Please report
        this bug:
        
        1 error occurred:
                * resource keycloak_user: id is a reserved field name
        
        
        
--- FAIL: TestAccKeycloakUser_federatedLink (0.34s)
```

Another option is adding a new field, e.g. `user_id`, to the schema and keep it in sync with the "internal" id.

Am I missing something or can anyone see a good approach here?

**Comment by tomrutsaert** [comment]
As Far as I know, You can not create a user with an id, The id will always be something else. Keycloak ignores the id field and creates a new id.
Needs to verified, I could be wrong.
Did you test if you can do a curl call with the id filled in? And check if the user was really created with that id?

**Comment by sj14** [comment]
Yes, look like you are right. I can send a specific id using curl and the user is successfully created but the specific id is ignored and a new one from Keycloak itself is used.

Thanks for your help 👍

**Comment by mrparkers** [comment]
I think Keycloak allows you to use your own ID when creating realms (the provider does this instead of letting Keycloak auto generate it).  But I believe that this is the only resource that allows this.
