### ISSUE TITLE
[Clients] - Add attributes

### ISSUE THREAD

**Issue by slavko-vega** [mrparkers/terraform-provider-keycloak#387]
Hi  @mrparkers,

we noticed that Clients are missing attributes, which are needed by our project. Currently the Attributes, as they are implemented, are limited to a subset of Client's properties which are used by Keycloak. What we actually need is possibility to add our custom attributes as it's possible for other resources.

Haven't seen that the issue is reported yet.  I'd like to contribute on its implementation, if you consider this as an issue.

Do you agree with that?

**Comment by mrparkers** [comment]
Hey @slavko-vega, that sounds great! I'd definitely accept a PR that adds an `attributes` argument to the `keycloak_openid_client` and/or `keycloak_saml_client` resources.

**Comment by slavko-vega** [comment]
Hey @mrparkers I'm glad to contribute on this issue and PR is prepared.

**Comment by mrparkers** [comment]
Closed via #589
