### ISSUE TITLE
SAML identity provider "Principal Type"

### ISSUE THREAD

**Issue by sandhose** [mrparkers/terraform-provider-keycloak#390]
The SAML identity providers have a "Principal Type" and "Principal Attribute" (when the Principal Type is not NameID) that can't be set in the `saml_identity_provider` resource right now

The two fields seems to be named `principalType` and `principalAttribute`.
The values in the UI seems to be `string:SUBJECT`, `string:ATTRIBUTE` and `string:FRIENDLY_ATTRIBUTE` for the type and an arbitrary string for the attribute. The attribute can only be set when the type is not  `SUBJECT`.

I haven't found anything specific to this in the API, so I'd guess it's in the [`config`](https://www.keycloak.org/docs-api/11.0/rest-api/index.html#_identityproviderrepresentation) map?

**Comment by mrparkers** [comment]
Fixed in #508
