### ISSUE TITLE
[openid_user_client_role_protocol_mapper] how to use the syntax  ${client_id}

### ISSUE THREAD

**Issue by semangard** [mrparkers/terraform-provider-keycloak#404]
Hello,

The tooltip into KeyCloak UI says for _openid_user_client_role_protocol_mapper_

    # Name of the claim to insert into the token. This can be a fully qualified name like 'address.street'. 
    # In this case, a nested json object will be created. To prevent nesting and use dot literally, escape the dot with backslash (\.). 
    # The special token ${client_id} can be used and this will be replaced by the actual client ID. 
    # Example usage is 'resource_access.${client_id}.roles'. 
    # This is useful especially when you are adding roles from all the clients (Hence 'Client ID' switch is unset) and you want client roles of each client stored separately.

I've tried : 
either   :    claim_name =  "resource_access.${client_id}.roles"
either   :    claim_name = join(".", ["resource_access", "${client_id}", "roles"])

And I got the ERROR : 

```
Error: Invalid reference
  on 030-appD.tf line 128, in resource "keycloak_openid_user_client_role_protocol_mapper" "D_to_A_api1_client__user_A_api_1_roles_mapper":
 128:     claim_name =  "resource_access.${client_id}.roles"

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name.

```

**Comment by tomrutsaert** [comment]
Try:

  claim_name = "resource_access.$${client_id}.roles"

This is not a bug in this provider.
This escaping info can be found in terraform documentation
https://www.terraform.io/docs/configuration-0-11/interpolation.html

**Comment by semangard** [comment]
OK sorry, my blame. It works.

**Comment by tomrutsaert** [comment]
No worries, It is a hard one to find in the docs tbh.
