### ISSUE TITLE
Module dependency not updated after renamed a module

### ISSUE THREAD

**Issue by semangard** [mrparkers/terraform-provider-keycloak#430]
Hello,

Into the TF state there is still an old reference to a module which has been renamed ::

![image](https://user-images.githubusercontent.com/57065741/98150302-b6913d00-1ece-11eb-8ba5-1c7262fd4ce4.png)

Here is the new reference ::
(please not that this is on a client and old references are still on objects related to that client : mappers, roles...)

![image](https://user-images.githubusercontent.com/57065741/98150432-ee988000-1ece-11eb-9101-58066c98ac26.png)

And here is the declaration of the module ::

![image](https://user-images.githubusercontent.com/57065741/98150488-0a038b00-1ecf-11eb-9858-5cf6836c8116.png)

**Comment by semangard** [comment]
If I comment the reference , nothing changes, none old reference is removed

**Comment by semangard** [comment]
If I destroy the object and rebuild it then I got the good new reference....

**Comment by mrparkers** [comment]
Module dependencies and how that information is persisted to state is something that terraform core handles, not individual providers.  Sorry, but I don't think there is anything we can do about this.

**Comment by dmeyerholt** [comment]
In general, when renaming existing resources or modules in a configuration you need to manually move them around in your state using `terraform state mv` to avoid destroying and recreating them. See [here](https://www.terraform.io/docs/commands/state/mv.html)
