### ISSUE TITLE
[ldap] - missing groups path in group-ldap-mapper

### ISSUE THREAD

**Issue by AdrienFromToulouse** [mrparkers/terraform-provider-keycloak#435]
Hi there,

it seems that the `group path` property is missing in the ldap group mapper.

Will make a PR to fix that.

<img width="813" alt="Screen Shot 2020-11-09 at 12 46 46" src="https://user-images.githubusercontent.com/1558229/98537623-cc658000-2289-11eb-9669-62ed8f427234.png">

Cheers,

**Comment by jokarls** [comment]
I would also like to have this feature. I have a parent admin group that I want to connect my AD groups too. That way I can add rolls to the parent group and they will trickle down to my mapped AD groups.

**Comment by AdrienFromToulouse** [comment]
At the moment I am stuck with the unit tests :(

I cannot yet figure out exactly what I am missing....
