### ISSUE TITLE
Support for automatic generation/import of all realm related resources

### ISSUE THREAD

**Issue by splatch** [mrparkers/terraform-provider-keycloak#442]
I have realm which have been managed through import/export functionality directly through Keycloak admin panel. While switching to terraform and this provider (thanks for awesome work!) I stubbed upon "verbosity" of realm representation.

Existing "terraform import" syntax seems to be insufficient for such large configuration object such realm and its derivatives (clients, protocols, mappers etc). That's why I'd like to begin discussion on how to quickly turn an existing realm into terraform resources without long and manual identifier tracing.

**Comment by mrparkers** [comment]
Hey @splatch.  This is a good question, and it's actually something that the Terraform core devs have been considering for a while.

Unfortunately, there isn't currently a perfect way to automatically generate Terraform code from an existing Keycloak deployment.  The closest thing there is right now is a project called [terraformer](https://github.com/GoogleCloudPlatform/terraformer).  Right now, terraformer appears to support a subset of this provider's resources, as you can see here: https://github.com/GoogleCloudPlatform/terraformer/tree/master/providers/keycloak

I'd recommend giving that a shot.  I haven't actually used this project before, but I know people who have used it and were successful, so hopefully that can help you out a bit.

**Comment by splatch** [comment]
@mrparkers Thank you very much for pointing out the terraformer support. I was aware of the terraformer existence but didn't know about keycloak module. It seems to be exactly what I been looking for. While it might not support all of the narrow elements it seems to automate most of the work needed to get started.
