### ISSUE TITLE
Multivalued user attributes mapping

### ISSUE THREAD

**Issue by lemaral** [mrparkers/terraform-provider-keycloak#451]
While using Multivalued user attributes mapping with ## delimiter as described in https://lists.jboss.org/pipermail/keycloak-user/2015-October/003493.html, if this value is set in the console: value1##value2, using the same value in terraform will show a difference, and none if the ## delimiter is removed (value1value2)
resource keycloak_user user {
  attributes = {
    somevalues = "value1##value2"
  }
}
shows a diff in terraform plan

resource keycloak_user user {
  attributes = {
    somevalues = "value1value2"
  }
}
shows no diff in terraform plan

**Comment by mrparkers** [comment]
I don't seem to have this issue on the latest version of the provider, testing against Keycloak 12.  Here's what I tried:

```hcl
resource keycloak_user user {
  realm_id = "test"
  username = "foo"
  attributes = {
    somevalues = "value1##value2"
  }
}
```

This configuration seems to work, and multiple runs of `terraform apply` shows no diff.

Can you try this again and see if you're still experiencing a problem?

**Comment by lemaral** [comment]
Thanks for trying, the problem is that the provider is not creating a multivalues attribute, the keycloak console is, through the use of the ## separator. If you set the attribute value to value1##value2 using the console, it will show as value1value2 in the provider. This is with the latest version of the provider and keycloak 11.0.2 (I don't think using keycloak 12 would change anything)

**Comment by unholyones** [comment]
Hi! I have found the same issue in my setup. In prod, we are using multivalue attributes for the user to divide permissions. Attribute, like 'somevalues = "value1##value2"', created by a provider not working for my SW in contrast to the same attribute created manually in UI. As a bad workaround, i am doing next to:
1. Create user and attribute 'somevalues = "value1##value2"' via provider.
2. In UI set same attribute manually.
3. Fix attribute to 'somevalues = "value1value2"' in tf file. In this case plan shows no diff.
