### ISSUE TITLE
[keycloak_custom_user_federation] config not allowing commas

### ISSUE THREAD

**Issue by PaulGgithub** [mrparkers/terraform-provider-keycloak#454]
If the `config` from `keycloak_custom_user_federation` contains a comma, the plugin will ignore everything after the comma from that config.

Example:
```
resource "keycloak_custom_user_federation" "custom_user_federation" {
  name        = "User adapter provider"
  realm_id    = keycloak_realm.realm.id
  provider_id = "user-adapter-provider"

  enabled     = true

  config = {
    configWithComma = "this works,this will be ignored"
  }
}
```

Debug (note `"configWithComma":["this works"]`):
```
2021-01-08T21:29:35.904+0200 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 
{
   "name":"User adapter provider",
   "providerId":"user-adapter-provider",
   "providerType":"org.keycloak.storage.UserStorageProvider",
   "parentId":"passwordless",
   "config":{
      "cachePolicy":[
         "DEFAULT"
      ],
      "configWithComma":[
         "this works"
      ],
      "enabled":[
         "true"
      ],
      "priority":[
         "0"
      ]
   }
}
```

This is most likely caused by splitting the config from comma [here](https://github.com/mrparkers/terraform-provider-keycloak/blob/master/provider/resource_keycloak_custom_user_federation.go#L85).

@tomrutsaert what was the reason for splitting by `,` ?

Thanks for this awesome provider!

**Comment by tomrutsaert** [comment]
I have no idea,
Has been a while.
Is most likely a mistake and thus a bug.
Feel free to make PR to change this behaviour and make test to proof it works
