### ISSUE TITLE
[Question] - when is the next release coming?

### ISSUE THREAD

**Issue by AdrienFromToulouse** [mrparkers/terraform-provider-keycloak#456]
Hi @mrparkers ,

there are many interesting things into Master as the moment that I would like to benefit from.

When do you plan to release the next version?

Thanks again for your work on this provider 👍 

Cheers 😷

**Comment by mrparkers** [comment]
Hey @AdrienFromToulouse, I just merged #452 which was the main blocker for the next release.  tomorrow, I'm going to spend some time merging open PRs that look good and cut a release.

apologies for the long wait!

**Comment by mrparkers** [comment]
https://github.com/mrparkers/terraform-provider-keycloak/releases/tag/v2.1.0 🚀
