### ISSUE TITLE
Can't delete broken KC instance

### ISSUE THREAD

**Issue by moisei** [mrparkers/terraform-provider-keycloak#457]
My KC instance is one of the resources in my TF script. The problem, if the instance is broken for some reason, I can't delete or recreate it, so basically, my entire infrastructure provided with this script can't be controlled by the TF anymore.
A simple way to reproduce: 
- Deploy KC with TF using terraform-provider-keycloak provider
- delete KC instance manually
- `terraform destroy`:  
```
keycloak_realm.wn_realm: Refreshing state... [id=webnews]
2021-01-10T17:24:37.779+0200 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 2021/01/10 17:24:37 [DEBUG] Login request: client_id=admin-cli&grant_type=password&password=Gfn%4012345&username=admin
2021/01/10 17:24:37 [ERROR] eval: *terraform.EvalRefresh, err: error logging in: error sending POST request to https://kc.example.com/auth/realms/master/protocol/openid-connect/token: 404 Not Found
2021/01/10 17:24:37 [ERROR] eval: *terraform.EvalSequence, err: error logging in: error sending POST request to https://kc.example.com/auth/realms/master/protocol/openid-connect/token: 404 Not Found

Error: error logging in: error sending POST request to https://kc.example.com/auth/realms/master/protocol/openid-connect/token: 404 Not Found


2021-01-10T17:24:37.956+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-10T17:24:37.956+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```

**Comment by mrparkers** [comment]
This doesn't seem like a provider issue to me.

Terraform keeps track of resources its aware of in state.  If you delete these resources manually, Terraform doesn't have a way to know that this happened without some assistance.  You can use `terraform state rm` to remove a resource from state if it no longer exists.  The Keycloak provider actually handles some of these cases for you - when we attempt to fetch a resource and get a 404 back, it gets removed from state so the provider knows that it needs to be recreated.

In this case, however, the particular problem you seem to be having is that the `master` realm doesn't exist anymore.  If you're using that realm for authentication and it doesn't exist, then you're likely to see errors like that.  There isn't a way for the Keycloak provider to gracefully recover from a scenario like that.

**Comment by moisei** [comment]
@mrparkers , Thank you for the quick reply. Indeed, the manual deletion is just an easy way to describe and to reproduce the issue.
The real problem is that if the authentication realm is broken for some reason then all the further update or destroy operations of the dependant resources are not possible anymore.  I agree it might be not the KK provider issue though

**Comment by mrparkers** [comment]
Yeah, if you think that's the issue, then there's definitely nothing the provider can do about that.  Successful authentication is the first step to managing any resources in Keycloak at all.

I wish you luck in getting your authentication realm restored!

**Comment by moisei** [comment]
@mrparkers I am doing more tests, and I think still there is something that could be fixed in the provider implementation.
`keycloak_realm` should know to wait for the master realm to be initialized. Currently, it just fails if the master realm is not available.
We worked around this issue by using a custom shell script querying the `https://${keycloak_host}/auth/realms/master/protocol/openid-connect/token`
