### ISSUE TITLE
Malformed version with RedHat SSO

### ISSUE THREAD

**Issue by Filirom1** [mrparkers/terraform-provider-keycloak#461]
Hello,

Using RedHat SSO I have the following errors, when doing a terraform plan:

```
Malformed version: 7.4.1.GA
```

Or on another cluster

```
Malformed version: 7.4.3.GA
```

It seems to be related to:

https://github.com/mrparkers/terraform-provider-keycloak/commit/25c8029904705565aa00f110749856a3041cca19

Kind regards
Romain

**Comment by guiadco** [comment]
I'm sorry to ask but is'that possible to generate a new release to use the provider ? because i have the same issue on your latest release 2.1.0 :)
