### ISSUE TITLE
Circular dependency between S3 storage and Keycloak Provider when upgrading to 0.13

### ISSUE THREAD

**Issue by lathspell** [mrparkers/terraform-provider-keycloak#485]
I have a terraform 0.12 project that uses the Keycloak provider and stores its terraform state in an S3 bucket. Now I’ve tried to update this project to terraform 0.13. It worked fine locally with “terraform.tfstate” but when trying to update the real installation I wouldn’t let me:

If I first try to upgrade the Keycloak plugin name it tells me that it cannot access the S3 storage yet:

```
 $ terraform state replace-provider registry.terraform.io/-/keycloak mrparkers/keycloak
Backend reinitialization required. Please run "terraform init".
Reason: Initial configuration of the requested backend "s3" 
...
```

If I first try to run “init” it can access the S3 storage, finds a reference to an unknown Keycloak 1.2.0 module there and does not know how to download it. Please note that my configuration already declares a dependency to keycloak-provider 2.2.0:

```
$ terraform init
Initializing modules...
- dev_realm_srt in ../../modules/realms/SRT
Initializing the backend...
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
- Finding hashicorp/keycloak versions matching "~> 1.20.0"...
- Finding mrparkers/keycloak versions matching ">= 2.2.0"...
- Finding latest version of -/keycloak...
- Installing mrparkers/keycloak v2.2.0...
- Installed mrparkers/keycloak v2.2.0 (self-signed, key ID C50867915E116CD2)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html
Error: Failed to install provider
Error while installing hashicorp/keycloak: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/keycloak
Error: Failed to install legacy providers required by state
Found unresolvable legacy provider references in state. It looks like these
refer to in-house providers. You can update the resources in state with the
following command:
    terraform state replace-provider registry.terraform.io/-/keycloak registry.terraform.io/mrparkers/keycloak
```

Any ideas how to resolve this?

I hope you don't mind that I cross-posted the question from https://discuss.hashicorp.com/t/circular-dependency-between-s3-storage-and-keycloak-provider-when-upgrading-to-0-13/20901, but maybe you can tell me if I could skip the "replace-provider" step if I manually search and replaced the registry strings in the S3 terraform.tfstate file?

**Comment by lathspell** [comment]
As a **workaround** I did the following:

1. downloaded the terraform.tfstate from the S3 bucket
2. adjusted "version", increased "serial"
3. replaced URLs with `sed -i -e 's/"provider.keycloak"/"provider[\\"registry.terraform.io\/mrparkers\/keycloak\\"]"/g' terraform.tfstate.FIXED`
4. uploaded the fixed tfstate to the S3 bucket

Then "terraform init" worked with the new config.

**Comment by dmeyerholt** [comment]
Hi,
 i'm not sure if it solves your particular problem, but we used the `terraform state replace-provider` command to successfully replace the provider URL in-place. We did not encounter similar problems using the s3 backend. Normally there should not be a circular dependency between the backend and the provider. However we migrated a while ago.

**Comment by mrparkers** [comment]
Yeah, I think `replace-provider` is the solution here.  I don't think there's any changes that I can make to this provider to help facilitate this upgrade process.

Feel free to respond if this still isn't working and we can try to work through it together.
