### ISSUE TITLE
[SAML client] - Support for SAML Signature Key Name

### ISSUE THREAD

**Issue by AdrienFromToulouse** [mrparkers/terraform-provider-keycloak#509]
👋 

filling the issue, will see if I can make a PR soon.

It seems that the `SAML Signature Key Name` property for SAML client is not supported.

Cheers!

**Comment by jjarman-infinity** [comment]
Hi it looks like there is no development work going on the pr. I have a pr which I think fixes it

[Pull Request](https://github.com/mrparkers/terraform-provider-keycloak/pull/588)

**Comment by mrparkers** [comment]
Closed via #588
