### ISSUE TITLE
terraform.tfstate in backend

### ISSUE THREAD

**Issue by volck** [mrparkers/terraform-provider-keycloak#517]
Hi,

We want to implement a workflow where we keep the whole terraform.tfstate in a kubernetes storagebackend(https://www.terraform.io/docs/language/settings/backends/kubernetes.html). As far as we can see, only the vault state is pushed to the backend(probably done by vault module?), but not the keycloak state. We would like both to be pushed.
Is this within the scope of this module, or should it be fixed elswehere?

**Comment by mrparkers** [comment]
Hey @volck 👋 

This doesn't seem like it would be within the scope of this provider.  Providers don't really deal with reading and writing state to a specific backend.  Rather, they simply act as a translation layer between Terraform configuration, Terraform state, and an upstream API (Keycloak, in this case).

I'm going to close this issue, but if you go into more detail about the problem you're trying to solve and provide me with some example configurations, I'd be happy to offer some suggestions for you.

Thanks!

**Comment by volck** [comment]
Hi! 

Thanks for your reply. Our issue is that we're seeing parts of the state being pushed to k8s, but not everything. This makes it more fragile than we'd like. If we could push the whole state of keycloak to the backend we'd be able to get the state from backend and not risk being in the situation in which a statefile is missing and we'll have to push changes to our keycloak outside opening hours. 


added zip of our current setup;
[somemodule.zip](https://github.com/mrparkers/terraform-provider-keycloak/files/6536791/somemodule.zip)


Here is our main

`
variable "keycloak_admin_username" {
  type = string
}
variable "keycloak_admin_password" {
  type = string
}

module "somemodule" {
  source                  = "../../modules/somemodule"
  keycloak_admin_password = var.keycloak_admin_password
  keycloak_admin_username = var.keycloak_admin_username
  keycloak_url            = "https://keycloak.lives.here"
  kubernetes_backend_env  = "ourkubernetesbackend"
  vault_secretengine = "localvaultsecretengine"
  vault_address = "https://vault.lives.here"
}
`

**Comment by mrparkers** [comment]
It's difficult to know for sure what the exact problem is, but one thing I'm noticing is that you're defining a `terraform` and `backend` block within your module.  I assume that this module is being invoked from a main file that also has a `terraform` and `backend` block defined.  This could be the source of your problem - as terraform expects that only a single backend is defined within the entire configuration, and it expects that your backend configuration not rely on variables.  Per https://www.terraform.io/docs/language/settings/backends/configuration.html:

```
There are some important limitations on backend configuration:

- A configuration can only provide one backend block.
- A backend block cannot refer to named values (like input variables, locals, or data source attributes).
```

What I typically do is define a single `terraform` and `backend` configuration at the root of my Terraform code, which is automatically inherited by modules that are consumed in this configuration (and nested modules as well).

I'd recommend giving that a try, unless there was a particular reason that you wanted the state of this Keycloak module to be separate from the state of your other Terraform code.  In which case, I might have more suggestions.
