### ISSUE TITLE
Is there a way to run this provider with Self Signed certificate against local deployment?

### ISSUE THREAD

**Issue by marcofranssen** [mrparkers/terraform-provider-keycloak#519]
I'm using a local deployment for testing with a selfsigned certificate on my keycloak url at keycloak.localhost.

Is there a way to ignore certificate errors in this provider?

Could we add a `ignore_cert_errors` variable to the provider block?

```hcl
provider "keycloak" {
  client_id = "admin-cli"
  username = var.keycloak_username
  password = var.keycloak_password
  url = "https://keycloak.localhost"
  ignore_cert_errors = true
}
```

Or is there another way to work around this?

**Comment by sl-benoitoyez** [comment]
I think the parameter you are asking for is already implemented under the name https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs#tls_insecure_skip_verify
