### ISSUE TITLE
Add additional realm fields

### ISSUE THREAD

**Issue by alexashley** [mrparkers/terraform-provider-keycloak#52]
It would be great to manage the email options for a realm; this is needed for "forgot password" emails and email verification.

<img width="982" alt="screen shot 2018-11-05 at 10 16 10 am" src="https://user-images.githubusercontent.com/9082799/48010767-d75a0880-e0e3-11e8-8c75-56e90c243171.png">

Another missing field is `offline_session_max_lifespan_enabled`. It controls whether [`offline_session_max_lifespan`](https://github.com/mrparkers/terraform-provider-keycloak/blob/master/provider/keycloak_realm.go#L120) is enforced:
> if you enable the option Offline Session Max Limited, then the offline token expires after 60 days regardless of using the offline token for a refresh token action (this value, Offline Session Max lifespan, can also be changed in the administration console in the Tokens tab under Realm Settings)

**Comment by alexashley** [comment]
Another useful field is password policy, which can be used even when federating from a custom provider (as long as the provider calls validate on the `PasswordPolicyManagerProvider`). 

https://www.keycloak.org/docs/latest/server_admin/index.html#_password-policies

**Comment by tomrutsaert** [comment]
fields from the screenshot (smtp server settings) were merged into master
Internationalization fields can be found in https://github.com/mrparkers/terraform-provider-keycloak/pull/124
and I am working and security defenses fields.

slowly we are getting all the fields

**Comment by mrparkers** [comment]
Looks like this is implemented now
