### ISSUE TITLE
Add support for role filtering in Scope tab (full_scope_allowed=false)

### ISSUE THREAD

**Issue by tomrutsaert** [mrparkers/terraform-provider-keycloak#539]
Add support for role filtering in Scope tab (full_scope_allowed=false).
Currently you are able to set full_scope_allowed on a client.
But when you put it on false, you want be able to define which roles you do want to filter in.
This is currently not possible.
This is not about client scopes, this is about Scope tab on a client(and in a client scope), which handles the role filtering in realm_access and resource_access claims.....

![image](https://user-images.githubusercontent.com/13900759/119789539-6cf05a00-bed3-11eb-8dec-31428612096e.png)

**Comment by cnaj** [comment]
You might want to check out the docs at https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/generic_client_role_mapper, this should provide the functionality you're looking for.

**Comment by tomrutsaert** [comment]
You are right, I missed this.
