### ISSUE TITLE
Support for darwin_arm64

### ISSUE THREAD

**Issue by MarS919** [mrparkers/terraform-provider-keycloak#541]
When trying to install, I get:

> Provider registry.terraform.io/mrparkers/keycloak v3.0.1 does not have a package available for your current platform, darwin_arm64.

**Comment by mrparkers** [comment]
Hi @MarS919, I just released v3.2.0-rc.0 to test the support for `darwin_arm64`.  Can you give that a try and let me know how that works?  I don't personally have a M1 Mac to test it myself.

**Comment by MarS919** [comment]
Thanks a lot @mrparkers, a quick basic test shows it works!
