### ISSUE TITLE
Incorrect checksum for 3.1.0 (terraform init fails)

### ISSUE THREAD

**Issue by imrekel** [mrparkers/terraform-provider-keycloak#543]
terraform init fails with
```
Error while installing mrparkers/keycloak v3.1.0: checksum list has unexpected
SHA-256 hash 9ea06230067fab526dac3048f30557f16dbf1dde747008b9e31a24acc6f82822
(expected ffc086194c59403678e66a0a429201414bd150cdbeea163d7a84f7f4826684b2)
```

(using terraform 0.14.7)

**Comment by mrparkers** [comment]
Yeah, the v3.1.0 release was accidentally removed when I was trying to remove other tags that were accidentally pushed.  I tried to resync it on the terraform registry with no luck.  I just pushed up v3.1.1, which should work fine.  It should be available shortly.

Apologies for the inconvenience

**Comment by imrekel** [comment]
No problem, thanks for the quick answer.
