### ISSUE TITLE
Missing docs for keycloak_ldap_role_mapper

### ISSUE THREAD

**Issue by Wiston999** [mrparkers/terraform-provider-keycloak#555]
Hello,

I've been searching in documentation about `keycloak_ldap_role_mapper` resource but doesn't seem to be documented.
It would be great to have it documented so it's easier for people know that the resource is actually implemented in this provider (I've spent like 20 minutes searching :sweat_smile: ) .

Thanks for the great work in the provider itself.

**Comment by tomrutsaert** [comment]
In the beginning of this provider, it was not requested to write documentation for resource. That is why still some resources are missing. (Although should be already added by @mrparkers)
(I think required actions are also still missing in the documentation)

Anyway, as tip: If you do not find it in the docs, it is always worth to take a look in the example directory:
https://github.com/mrparkers/terraform-provider-keycloak/tree/master/example

But in your case, even that would not have worked, as I can also not immediately find an example of keycloak_ldap_role_mapper

**Comment by mrparkers** [comment]
Thanks for the heads up, I can try to get to this for the next release.

**Comment by mrparkers** [comment]
These will be added in the next release.  Thanks for the report!
