### ISSUE TITLE
provider client authentication scopes

### ISSUE THREAD

**Issue by m-v-k** [mrparkers/terraform-provider-keycloak#558]
We run into issues with authentication and max jwt size for our nginx proxy, this could be easily resolved by using a scope to target our tokens.

We would like support for optional 'scope'  input for the provider configuration (client credentials grant) so that the oauth scope field can be used for client credentials.

We can contribute, but before we invest time en energy i would like to hear your thoughts and if you are open for such a pr?

result would be something like this;
```
provider "keycloak" {
    client_id     = "terraform"
    client_secret = "884e0f95-0f42-4a63-9b1f-94274655669e"
    url           = "http://localhost:8080"
    scope         = "openid customscope"
}
```

**Comment by dmeyerholt** [comment]
Hi @m-v-k,
Depending on your requirements please check [this](https://github.com/mrparkers/terraform-provider-keycloak/issues/483) issue as well. The admin Part of keycloak has some hard-coded defaults relying on admin roles being present in the token.

**Comment by m-v-k** [comment]
indeed this approach seems to work just fine, although i can't use the admin-cli anymore for normal cli commands with user authentication but thats fine for now.
thanks a million @dmeyerholt for the golden tip!

**Comment by mrparkers** [comment]
Although this issue is closed, I would still accept a PR to add a `scopes` provider attribute if you want to specify custom scopes for the oauth2 flow that is used to get an access token.
