### ISSUE TITLE
Facebook identity provider

### ISSUE THREAD

**Issue by MatteoInfi** [mrparkers/terraform-provider-keycloak#567]
Cannot find Facebook as identity provider: https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/oidc_google_identity_provide

I have tried by using this: 

```
resource "keycloak_oidc_facebook_identity_provider" "facebook_identity" {
  realm         = keycloak_realm.myrealm.id
  client_id     = "1234567889" //
  client_secret = "clientSecret"
  enabled   = true
  sync_mode     = "IMPORT"
}
```

but no luck.

**Comment by tomrutsaert** [comment]
Is not implemented.
but you can use:
https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/oidc_identity_provider
Any fields that are missing in the resource but need for facebook idp can be added via extra_config.
For any required fields in the resource that you do not need for facebook idp, you can just fill in something random. or for example "Not applicable"

**Comment by MatteoInfi** [comment]
Gotcha, thanks
