### ISSUE TITLE
Clients Backchannel* settings support

### ISSUE THREAD

**Issue by myardyas** [mrparkers/terraform-provider-keycloak#568]
This plugin is really cool. Thanks! Implementing it in our environment. Is there any chance to support client's backchannel* settings like:
- Backchannel Logout URL
- Backchannel Logout Session Required
- Backchannel Logout Revoke Offline Sessions
?

**Comment by myardyas** [comment]
@mrparkers Thanks for implementing, but settings look like missed up -)
https://github.com/mrparkers/terraform-provider-keycloak/blob/v3.4.0/provider/resource_keycloak_openid_client.go#L299-300

**Comment by mrparkers** [comment]
Oops, I fixed this in #600
