### ISSUE TITLE
Add support for "Use Refresh Tokens" to keycloak_oidc_client

### ISSUE THREAD

**Issue by whiskeysierra** [mrparkers/terraform-provider-keycloak#570]
The *OpenID Connect Compatibility Modes* section of OIDC clients has the following properties:

![image](https://user-images.githubusercontent.com/429981/128169254-7a209c23-82ea-485c-8016-462842012634.png)

Judging from the form element's name, the client attribute seems to be called `useRefreshTokens` (I haven't found anything in the official REST docs.)

**Comment by whiskeysierra** [comment]
Correction, the client attribute is called `use.refresh.tokens` (after checking the API manually).

**Comment by phungy** [comment]
Hi,
I have question about the new attribute "use_refresh_tokens" introduced in recent release version 3.3.0
Today I ran a terraform plan with the latest version of mrparkers/keycloak (3.3.0) and got change notification about client
For example:
` Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or
respond to these changes.

   # keycloak_openid_client.my-client will be updated in-place
  ~ resource "keycloak_openid_client" "my-client" {
        id                                       = "d9804e6c-c740-3b18-bb47-af4d01f1c47b"
        name                                     = "my-client"
      ~ use_refresh_tokens                       = false -> true
        # (25 unchanged attributes hidden)
    }`

Before version 3.3.0 that attribute doesn't exist so we didn't set it. But in version 3.3.0 its default value is set at True now.

I don't know if there is any difference with "Use Refresh Tokens For Client Credentials Grant" attribute that is already there. 
![image](https://user-images.githubusercontent.com/88713989/128849521-a3eed83d-950e-4681-a601-75b72d2fc1ed.png)

Now the default value is set at True. Does it mean we have to set that attribute at False to keep the existing behavior for our project?

Thanks for your guidance.
Phung Nguyen
