### ISSUE TITLE
Unable to configure oidc-role-idp-mapper using keycloak_custom_identity_provider_mapper

### ISSUE THREAD

**Issue by MartinsVi** [mrparkers/terraform-provider-keycloak#571]
Hi,

When I try to setup "Claim to Role" mapper for oidc identity provider, terraform ignores Claim, ClaimValue and Role parameters specified in "extra_config"

I suspect this is related to the same issue mentioned in https://github.com/mrparkers/terraform-provider-keycloak/issues/546 and https://github.com/mrparkers/terraform-provider-keycloak/issues/520
The only parameter that is actually applied is "syncMode"

This is the actual terraform config I was trying:
```
resource "keycloak_custom_identity_provider_mapper" "master_azure_ad_test" {
  realm                    = keycloak_realm.master.id
  name                     = "test"
  identity_provider_alias  = keycloak_oidc_identity_provider.master_azure_ad.alias
  identity_provider_mapper = "oidc-role-idp-mapper"

  // none of these creates claim to role mapping

  extra_config = {
    Claim      = "groups"
    ClaimValue = "60da9df6-5bd9-461f-a637-945be8c596c6"
    Role       = "admin"
    syncMode   = "INHERIT"
  }

  //  extra_config = {
  //    claim = "groups"
  //    "claim.value" = "60da9df6-5bd9-461f-a637-945be8c596c6"
  //    role = "admin"
  //    syncMode = "INHERIT"
  //  }

}
```

This is how mapper looks in admin console
![image](https://user-images.githubusercontent.com/47249890/128341204-32694aac-218e-41ad-8b7d-cc7e06da15f9.png)

Am I doing something wrong (besides using "master" realm) or is this an issue with keycloak provider?
Provider version: v3.2.1

**Comment by tomrutsaert** [comment]
Yes, I will try it tomorrow

**Comment by tomrutsaert** [comment]
All works good at my end with my custom idp mapper
the code change LGTM

**Comment by mts-dyt** [comment]
Hi @tomrutsaert ,
Can you please share you terraform block used to create this identity_provider_mapper.
I tried by using the code provided but stil have empty value for claim/value/role in interface (I use keycloak provider v4.0.0)
Thanks a lot

**Comment by tarekzemmouri** [comment]
Hi,
I'am trying to define "User Attribute Name" value, but seems that it's still blank after the definitions.
This is my Keycloak provider version.
```
    keycloak = {
      source = "mrparkers/keycloak"
      version = "4.4.0"
     }
```
     
     And the configuration that i use:
```
     resource "keycloak_custom_identity_provider_mapper" "oidc" {
  realm                    = keycloak_realm.realm.id
  name                     = myCustomName
  identity_provider_alias  = keycloak_oidc_identity_provider.realm_identity_provider.alias
  identity_provider_mapper = "oidc-user-attribute-idp-mapper"

  extra_config = {
    syncMode               = "INHERIT"
    claim                  = "myClaim"
	  attribute     = "myAttribute"
		userAttribute = "myUserAttribute"
  }
}
```
Claim works juste fine but the "User Attribute Name" having some trouble defining it, still blank, any help is appreciated.
![image](https://github.com/user-attachments/assets/427ee818-fbe7-415f-928b-2f61f7912442)
