### ISSUE TITLE
Custom identity providers from deployed jar

### ISSUE THREAD

**Issue by MatteoGioioso** [mrparkers/terraform-provider-keycloak#581]
Hello

is it possible to configure a `keycloak_oidc_identity_provider` using providers from external jars?

We are using this one: https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider

If this is not available do you guys accept PR?

**Comment by tomrutsaert** [comment]
Yes,

Take a look at extra_config param in documentation
https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/oidc_identity_provider
Any fields that is required in this terraform-provider-keycloak but not needed for the custom idp provider, just fill something bogus.

example:

```
resource "keycloak_realm" "realm" {
  realm   = "my-realm"
  enabled = true
}

resource "keycloak_oidc_identity_provider" "my_custom_identity_provider" {
  realm             = keycloak_realm.realm.id
  alias             = "my-custom-idp"
  authorization_url = "https://not_needed.com"
  client_id         = "clientID"
  client_secret     = "not_needed"
  token_url         = "https://tokenurl.com"

  extra_config = {
    "myCustomParam" = "customValue"
  }
}
```


We are always open to a PR to improve this.

Please close the ticket if this answers your question.

**Comment by MatteoGioioso** [comment]
@tomrutsaert hey, thanks for the answer

so, does it work with the custom jar as well? That jar, if deployed, will add Apple to the list of identity providers in the Keycloak console. 
I will try to test it.

Thanks

**Comment by tomrutsaert** [comment]
yes it will work,
I use it for a couple custom idps myself in several projects

**Comment by MatteoGioioso** [comment]
@tomrutsaert ok, thanks. I guess this answer my question.

**Comment by tomrutsaert** [comment]
Most important thing to set for you is the provider_id param. See documentation for more info

**Comment by MatteoGioioso** [comment]
@tomrutsaert oh, I completely missed that, thanks for clarifying this :+1:
