### ISSUE TITLE
Is it possible to update SMTP settings for the master realm?

### ISSUE THREAD

**Issue by tmyroadctfig** [mrparkers/terraform-provider-keycloak#597]
I guess this is related to #427. I'm trying to update the SMTP settings for the `master` realm as part of a multi-realm deployment. Is that possible? Terraform fails trying to create the `master` realm because it already exists:
```
keycloak_realm.master_realm: Creating...

Error: error sending POST request to /auth/admin/realms: 409 Conflict. Response body: {"errorMessage":"Conflict detected. See logs for details"}

  with keycloak_realm.master_realm,
  on keycloak-smtp.tf line 1, in resource "keycloak_realm" "master_realm":
   1: resource "keycloak_realm" "master_realm" {
```

I'm configuring the master realm to add in oauth clients, etc, but I'm also keen to set the SMTP settings automatically If I understand the suggestions in #427 correctly I could import the realm to avoid the conflict, but it wouldn't be possible to configure the SMTP settings automatically via TF that way. Any pointers would be appreciated :)

Here's my keycloak-smtp.tf file:
```
resource "keycloak_realm" "master_realm" {
  realm                   = "master"
  enabled                 = true
  display_name            = "master realm"
  display_name_html       = "<b>master realm</b>"

  smtp_server {
    host = data.aws_ssm_parameter.keycloak_smtp_host.value
    from = "noreply@${local.workspace["saas_domain"]}"
    ssl  = true

    auth {
      username = data.aws_ssm_parameter.keycloak_smtp_user.value
      password = data.aws_ssm_parameter.keycloak_smtp_password.value
    }
  }
}
```

**Comment by mrparkers** [comment]
Right now, realm SMTP settings are controlled by the `keycloak_realm` resource, so there isn't a great flow for configuring this on a pre-existing realm such as `master`.  Your best bet is to import this configuration into state so Terraform can start managing it.  You can do this via the `terraform import` command:

```
$ terraform import keycloak_realm.master_realm master
```

**Comment by x4121** [comment]
Hi, I'm trying to achieve the same but get an error when running `terraform import`

```
terraform import keycloak_openid_client.account myrealm/very-long-numerical-id
keycloak_openid_client.account: Importing from ID "myrealm/very-long-numerical-id"...

Error: nil entry in ImportState results. This is always a bug with
the resource that is being imported. Please report this as
a bug to Terraform.
```

I get the same error when running `terraform import keycloak_openid_client.account myrealm/account`

Tried it with `v3.3.0` and `v3.5.1` in Terraform `0.14.11`

Is there something I'm doing wrong?

**Comment by tculp** [comment]
@mrparkers Would you consider adding an 'import' field to the keycloak_realm resource, similarly to https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/openid_client#import ? This would be very helpful and I believe would solve this issue
