### ISSUE TITLE
Data Resource to Fetch All Roles from a Client

### ISSUE THREAD

**Issue by StuxxNet** [mrparkers/terraform-provider-keycloak#619]
Good evening,

Is there any data resource that I can use to get all the roles from a specific client to use this list as parameter while creating a group?

Currently I'm struggling to create multiple groups with multiple roles because I couldn't find a way to create a proper array. I know that I can separate all this configuration in different variables, but it wouldn't be nice to maintain the code.

My variable is:

```terraform
variable "group_roles_mapping" {
  description = "Necessary information to create the mapping between groups and client roles a specific realm"
  default = {
    realm_id     = "Workbench"
    groups       = [{
      name        = "git-admin"
      client_id   = "git-dev"
      client_roles = ["role1", "role2", "role3"]
    },
    {
      name         = "homepage-admin"
      client_id    = "homepage-dev"
      client_roles = ["role1", "role2", "role3"]
    }]    
  }
}
```

If I could fetch, for example, in a single data resource, all the roles set to a client I could easily just inform the "client-id name", get the "id" from terraform using the data-source and then grep all the roles to create a group. Currently I'm working on the provisioning of an admin group, and I couldn't find a way to include all the client-roles in a single group. 

Is there any other approach that I can use?

**Comment by asilvanovich** [comment]
Same issue here. I need to import default client role ids somehow. @mrparkers is it possible to do it?
