### ISSUE TITLE
Add "Sync Settings" fields to keycloak_custom_user_federation resource

### ISSUE THREAD

**Issue by puzzlermike** [mrparkers/terraform-provider-keycloak#652]
Hi!

currently the only way to activate the "changedSyncPeriod" and "fullSyncPeriod" is by using the generic "config" field, e.g.:

```
resource "keycloak_custom_user_federation" "legacy_user_federation" {
    name        = "legacy-user-storage"
    realm_id    = keycloak_realm.legacy_realm.id
    provider_id = "legacy-user-storage"
    enabled     = true

    config = {
        "search.url"        = "https://legacy-api/legacy/api/users"
        "api.key"           = "<secret>"
        "changedSyncPeriod" = 60
        "fullSyncPeriod"    = 3600
    }
}
```

In my opinion it would be more convenient and transparent to set the options by using dedicated fields like "changed_sync_period" and "full_sync_period", for example:

```
resource "keycloak_custom_user_federation" "legacy_user_federation" {
    name                = "legacy-user-storage"
    realm_id            = keycloak_realm.legacy_realm.id
    provider_id         = "legacy-user-storage"
    enabled             = true
    changed_sync_period = 60
    full_sync_period    = 3600

    config = {
        "search.url" = "https://legacy-api/legacy/api/users"
        "api.key"    = "<secret>"
    }
}
```
Would it be okay to create a pull request for that or is such a change not wanted?

Thank you!

**Comment by mrparkers** [comment]
Hi @puzzlermike, PRs are definitely welcome for changes like this.  As newer versions of Keycloak come out, sometimes configuration attributes like these are added, and we never get around to backfilling that support on the terraform side.  `config` is convenient in this way, but I agree that officially supported top-level attributes would be better.  I'd be happy to review a PR if you want to submit one for this.
