### ISSUE TITLE
docs not linked correctly, probable cause for broken IntelliJ code completion

### ISSUE THREAD

**Issue by mrohlof-protofy** [mrparkers/terraform-provider-keycloak#673]
**Introduction:**
IntelliJ IDEA's plugin "Terraform and HCL" has the functionality to point you to the correct documentation page. 

![image](https://user-images.githubusercontent.com/98380964/158605414-4927fc26-171e-40c2-a86c-87f74f681d3e.png)

**Expected behaviour:**
The link should point to the actual location: https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/role

**Actual behaviour:**
The links point to https://www.terraform.io/docs/providers/keycloak/r/role.html, which really does not work.

**Side effects:**
I cannot be sure but I suspect this error is also the reason why "Terraform and HCL" code completion does not work for this provider:
![image](https://user-images.githubusercontent.com/98380964/158606627-51a0ea92-92a8-4703-9401-6279366aef95.png)

**Comment by mrparkers** [comment]
Hi @mrohlof-protofy, thanks for opening the issue.  I agree that this is unfortunate, but I don't think that there is anything that I can do with this provider to fix the problem.  If you have any ideas, feel free to let me know and I'd be happy to re-open this issue.

Thanks!
