### ISSUE TITLE
keycloak_custom_user_federation ressource fails with for_each

### ISSUE THREAD

**Issue by sl-cloud-platform** [mrparkers/terraform-provider-keycloak#682]
Since version 3.8.0 using for_each fails when it is used with keycloak_custom_user_federation:

This terraform code works in 3.7.0 and fails in 3.8.0:
```
resource "keycloak_custom_user_federation" "custom_user_federation" {
  for_each    = var.custom_federations
  ...
}
```

The error raised by the provider is:
```
Error: strconv.Atoi: parsing "": invalid syntax
with keycloak_custom_user_federation.custom_user_federation["xxx"],
```

**Comment by mrparkers** [comment]
Hi @sl-cloud-platform, sorry about this issue.  Can you tell me what version of Keycloak you're using?  Also, does this only fail when you create these resources via `for_each`?

I think I have a pretty good idea of what's wrong here, but I'm not able to reproduce this myself locally.  So these answers will help me figure this out for you.

Thanks!

**Comment by mrparkers** [comment]
Hi @sl-cloud-platform, sorry about this issue.  Can you tell me what version of Keycloak you're using?  Also, does this only fail when you create these resources via `for_each`?

I think I have a pretty good idea of what's wrong here, but I'm not able to reproduce this myself locally.  So these answers will help me figure this out for you.

Thanks!

**Comment by sl-cloud-platform** [comment]
HI @mrparkers,

we are currently using Keycloak v 17.0.0. It seems that this is the only ressource with the problem, because we are using many other ressources with `for_each` also.

**Comment by mrparkers** [comment]
Hi again @sl-cloud-platform, can you give v3.8.1 a try to see if this issue is still affecting you?

**Comment by sl-cloud-platform** [comment]
Hi @mrparkers, i will try it this week and then give you feedback.

**Comment by sl-cloud-platform** [comment]
Hi @mrparkers, thanks a lot - it is working again.
