### ISSUE TITLE
Support for keycloak 18.0.0

### ISSUE THREAD

**Issue by LmV4corbeau** [mrparkers/terraform-provider-keycloak#683]
Hello people,
Keycloak released Keycloak 18.0.0 in April this year and posted a new [release plan on their site](https://www.keycloak.org/2022/03/releases.html)

In the new version there are changes in the RestAPI of keycloak.
Currently, I have noticed that `/auth` has been removed from the paths.
Unfortunately, the `/auth` in the keycloak provider is not an optional element in the path.
I would like to suggest adding this part of the Rest route to the keycloak URL and removing it from the code.

So that users of keycloak 16 specify a URL like `https//127.0.0.1:8443/auth` and keycloak 18 only specifies `https//127.0.0.1:8443`.

**Comment by LmV4corbeau** [comment]
Keycloak 18 Container: quay.io/keycloak/keycloak:18.0.0

**Comment by mrparkers** [comment]
Hi @LmV4corbeau, I think you can address this by setting the [`base_path`](https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs#base_path) provider attribute to an empty string.  Right now, it defaults to `/auth`.

Please let me know if this solves your issue.  Thanks!

**Comment by LmV4corbeau** [comment]
Hi @mrparkers 
For my case, creating a realm, multiple oidc clients, groups, roles, a saml client and oidc identity provider your proposed solution works.

**Comment by LmV4corbeau** [comment]
Thanks for the easy solution
