### ISSUE TITLE
keycloak_ldap_user_federation with master realm is not working

### ISSUE THREAD

**Issue by spidersouleater** [mrparkers/terraform-provider-keycloak#694]
It's not possible to create a LDAP user federation provider within the Realm "master", anymore.

The problem occurs with the Image "quay.io/keycloak/keycloak:18.0.0-legacy". I'm using the Version 3.8.1 of the terraform-provider-keycloak.

Minimal example to reproduce the Problem:
```
data "keycloak_realm" "master" {
    realm = "master"
}

resource "keycloak_ldap_user_federation" "ldap_user_federation" {
  name     = "openldap"
  realm_id = data.keycloak_realm.master.id
  enabled  = true

  username_ldap_attribute = "cn"
  rdn_ldap_attribute      = "cn"
  uuid_ldap_attribute     = "entryDN"
  user_object_classes     = [
    "simpleSecurityObject",
    "organizationalRole"
  ]
  connection_url          = "ldap://openldap"
  users_dn                = "dc=example,dc=org"
  bind_dn                 = "cn=admin,dc=example,dc=org"
  bind_credential         = "admin"

  connection_timeout = "5s"
  read_timeout       = "10s"

  kerberos {
    kerberos_realm   = "FOO.LOCAL"
    server_principal = "HTTP/host.foo.com@FOO.LOCAL"
    key_tab          = "/etc/host.keytab"
  }
}
```

**Comment by EvgeniyBlinov** [comment]
+1
@spidersouleater Did you found any workaround solution?

**Comment by spidersouleater** [comment]
Hi mrparkers, thanks for your help. 

When executing the example configuration no error message seems to appear and everything has been configured correctly. But when you take look in the Keycloak-GUI you can see that "LDAP user federation provide" has not been created. 


**keycloak-18.0.2-legacy** 

- terraform-provider-keycloak 3.9.0

The problem still exists in the recent versions. You can see in the Keycloak Admin Console the missing provider after the Terrafrom execution.

![gui-18 0 2-legacy](https://user-images.githubusercontent.com/11627148/177188428-6b3ccc3e-104e-4110-97d1-ccf23bdadad1.png)

Here are the logs:

- [terraform-18.0.2-legacy.log](https://github.com/mrparkers/terraform-provider-keycloak/files/9040885/terraform-18.0.2-legacy.log)
- [keycloak.txt](https://github.com/mrparkers/terraform-provider-keycloak/files/9040889/keycloak.txt)
- [cmd.txt](https://github.com/mrparkers/terraform-provider-keycloak/files/9040906/cmd.txt)
 
**keycloak-17.0.1-legacy**

- terraform-provider-keycloak 3.9.0


This seems to be the last Version where everything is fine. You can see in the Keycloak Admin Console the created Provider after Terraform install.

![gui-17 0 1-legacy](https://user-images.githubusercontent.com/11627148/177191579-bbf1ba7e-da0b-42a9-801c-c0a3e2b2e559.png)

Here are the logs:

- [terraform-17.0.1-legacy.log](https://github.com/mrparkers/terraform-provider-keycloak/files/9041003/terraform-17.0.1-legacy.log)
- [cmd.txt](https://github.com/mrparkers/terraform-provider-keycloak/files/9041005/cmd.txt)
- [keycloak.log](https://github.com/mrparkers/terraform-provider-keycloak/files/9041004/keycloak.log)


I could find out that Keycloak-18-legacy use a UUID for the Master-Realm and not anymore the String representation "master". That could maybe cause the problems we have.

**Comment by kelimutu** [comment]
+1

**Comment by mrparkers** [comment]
Sorry for taking so long on this.  The root problem here is that Keycloak 18 changed the internal ID of the default `master` realm - it used to be `master`, but now it's a random GUID.  So the provider was making assumptions about the internal ID of this realm, which was causing this issue.

I've opened #707 to fix this.

**Comment by mrparkers** [comment]
This is fixed in `v3.9.1`

**Comment by spidersouleater** [comment]
Hi mrparkes,

i have tested the bugfix version and everything seems fine, now.

Thank you for your help.

**Comment by mrparkers** [comment]
Of course, thank you for your help with the debugging effort!  It saved me a lot of time since I didn't have to do much research to fix this.
