### ISSUE TITLE
Feature : Documentation for brute force protection

### ISSUE THREAD

**Issue by yanis-incepto** [mrparkers/terraform-provider-keycloak#706]
Hello,
I didn't fiond any information about the brute force detection on your documentation on terraform's registry.
Could it be possible to add one please ?

**Comment by Korsarro69** [comment]
Hello,

See the realm documentation here : https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/realm

You already have an object brute_force_detection inside security_defenses, with all properties existing in Keycloak

**Comment by yanis-incepto** [comment]
Hello, Thanks you !
