### ISSUE TITLE
Define logging level

### ISSUE THREAD

**Issue by avnerv** [mrparkers/terraform-provider-keycloak#708]
Hello,
I didn't find any information about configuring the logging level on keycloak.
Please advice.

**Comment by liamkinne** [comment]
Hi @avnerv, I believe the logging level has to be set when Keycloak starts up. So it's not possible to set the logging level through the API.

**Comment by mrparkers** [comment]
Yes, it looks like @liamkinne is correct, I don't think there's an API that the provider can use to set Keycloak's log level.  You'll have to set it yourself when deploying it.
