### ISSUE TITLE
new data source request "keycloak_openid_client_scope"

### ISSUE THREAD

**Issue by Marcus-James-Adams** [mrparkers/terraform-provider-keycloak#731]
Currently, the resource  "keycloak_openid_client_scope" allows you to create new resources and returns the client_scope_id

However, if you  are working on either keycloak_openid_user_client_role_protocol_mapper or keycloak_openid_user_attribute_protocol_mapper for any of the built-in client scopes you need the client_d of the existing scope.

Currently, you can work around it by having the following code block
```hcl
resource "keycloak_openid_client_scope" "roles" {
  realm_id               = keycloak_realm.myrealm.id
  name                   = "roles"
}
resource "keycloak_openid_user_client_role_protocol_mapper" "user_client_role_mapper" {
  realm_id        = keycloak_realm.myrealm.id
  client_scope_id = keycloak_openid_client_scope.roles.id
  name            = "client roles"
  claim_name      = "resource_access.$${client_id}.roles"
}
```

and then terraform importing  keycloak_openid_client_scope.roles realm/id

However, this then breaks good practice rules of automation by introducing manual steps

If we had a data source to return the id it would remove the need for manual steps

## Example resource

```hcl
resource "keycloak_openid_client_scope" "roles" {
  realm_id               = keycloak_realm.myrealm.id
  name                   = "roles"
}
```

### Argument-reference
- realm_id - (Required) The realm this role exists within.
- name - (Required) The name of the role.

### Attributes Reference
- id - (Computed) The unique ID of the role, which can be used as an argument to other resources supported by this provider.

**Comment by mrparkers** [comment]
Hi @Marcus-James-Adams, thanks for the feature request.  I've implemented this in #743.  This will be released in v4.0.0 some time later this week.
