### ISSUE TITLE
Create an initial password when creating a user

### ISSUE THREAD

**Issue by Floby** [mrparkers/terraform-provider-keycloak#76]
This is less a feature request than a mergeability poll, as I'm very much inclined to submit a pull request for this.

My feature would be

+ When a user is created and `initial_password` is set
A call to `/users/{user_id}reset-password` is made to initialize a password.

+ When a user is updated and `initial_password` is set
No further call is made

+ When `initial_password` is not set, do as is done now.

Would you accept such a feature ?

**Comment by Floby** [comment]
It's exactly that :)

You're right, I'm not sure either if the password is required to be
temporary. This is no problem for me as this fits my use case but it might
indeed be tricky to test.

Le mer. 2 janv. 2019 à 20:28, Michael Parker <notifications@github.com> a
écrit :

**Comment by alexashley** [comment]
There's a `temporary` field on the [`CredentialRepresentation`](https://www.keycloak.org/docs-api/4.8/rest-api/index.html#_credentialrepresentation) object. It's part of the payload for the initial [user post](https://www.keycloak.org/docs-api/4.8/rest-api/index.html#_users_resource). I've used it before to setup test users that didn't require password resets.
