### ISSUE TITLE
 401 Unauthorized error

### ISSUE THREAD

**Issue by romijung** [mrparkers/terraform-provider-keycloak#90]
@mrparkers Thank you for providing terraform provider for keycloak.
I would like to use this plugin for my keycloak.
but when I tried to use it, I have 401 Unauthorized error.

I was assuming that my keycloak configuration was  wrong. ( I gave admin role to the keycloak client )
but when I tested with keycloak plugin provided from https://github.com/tazjin/terraform-provider-keycloak, it's working properly.

it seems like that tazjin's repo is no longer maintained, I would like to try your plugin.

can you please check if you can give me advise...

** version information **
terraform : v0.11.11
terraform provider keycloak : v1.4.0
keycloak version : 4.7.0

** my test code **
```
provider "keycloak" {
    client_id         = "terraform"
    client_secret  = "xxxxxxx"
    url                 = "https://xxxx.com"
}

resource "keycloak_realm" "iot_sso" {
    realm   = "iot-sso"
}
```

** terraform apply error **
```
* keycloak_realm.iot_sso: error sending GET request to /auth/admin/serverinfo: 401 Unauthorized
```

** terraform import error **
```
$  ~/terraform1111 import keycloak_realm.iot_sso iot-sso
keycloak_realm.iot_sso: Importing from ID "iot-sso"...
keycloak_realm.iot_sso: Import complete!
  Imported keycloak_realm (ID: iot-sso)
keycloak_realm.iot_sso: Refreshing state... (ID: iot-sso)

Error: keycloak_realm.iot_sso (import id: iot-sso): 1 error(s) occurred:

* import keycloak_realm.iot_sso result: iot-sso: keycloak_realm.iot_sso: error sending GET request to /auth/admin/realms/iot-sso: 401 Unauthorized
```

Romi

**Comment by romijung** [comment]
I found the reason,,
I didn't create client in `MASTER` realm, that's why I had 401 error

**Comment by mrparkers** [comment]
Yeah, one of the differences between the two providers is that this one requires you to auth against the `master` realm.  #88 was opened to address this, allowing you to use whatever realm you want to auth against Keycloak.

Sorry for the inconvenience!  I'd suggest keeping an eye on that PR so you can change your configuration back to what it was before once it is merged.
